// Code generated by schemagen; DO NOT EDIT.

package cutouts

import (
	"github.com/pkg/errors"

	"github.com/wesen/yapp-encl-resolver/pkg/yappgen/decode"
)

// CutoutsItem describes the cutouts schema.
type CutoutsItem struct {
	// Which face of the enclosure
	Face string `yaml:"face"`
	// Horizontal position along the face from the left edge (mm). Used by all faces: base, lid, front, back, left, right.

	FromFaceLeft float64 `yaml:"from_face_left"`
	// Vertical position from the bottom edge of the face (mm). Required for side faces (front, back, left, right). Not valid for horizontal faces (base, lid).

	FromFaceBottom *float64 `yaml:"from_face_bottom,omitempty"`
	// Depth position from the back edge of the face (mm). Required for horizontal faces (base, lid). Not valid for side faces (front, back, left, right).

	FromFaceBack *float64 `yaml:"from_face_back,omitempty"`
	// Cutout width (set to 0 for circles)
	Width *float64 `yaml:"width,omitempty"`
	// Cutout length (set to 0 for circles)
	Length *float64 `yaml:"length,omitempty"`
	// Corner/circle radius (set to 0 for rectangles)
	Radius *float64 `yaml:"radius,omitempty"`
	// Cutout shape (maps to YAPP shape flag)
	Shape string `yaml:"shape"`
	// Cutout depth (defaults to shell thickness)
	Depth *float64 `yaml:"depth,omitempty"`
	// Rotation angle in degrees
	Angle *float64 `yaml:"angle,omitempty"`
	// Polygon preset shape name (required when shape=polygon). Options: hexagon, arrow, 6pt_star, iso_triangle, iso_triangle2, triangle, triangle2
	Polygon *string `yaml:"polygon,omitempty"`
	// Ventilation mask to apply to the cutout opening. Uses predefined patterns from YAPP: honeycomb, hex_circles, circles, squares, bars, offset_bars. Optionally adjust placement within the opening using offsets and rotation.

	Mask *CutoutsItemMask `yaml:"mask,omitempty"`
	// Coordinate system: pcb (yappCoordPCB, default), box (yappCoordBox), box_inside (yappCoordBoxInside)
	Coordinate *string `yaml:"coordinate,omitempty"`
	// Origin placement: global (yappOrigin/yappGlobalOrigin, default), center (yappCenter), alt (yappAltOrigin/yappLeftOrigin)
	Origin *string `yaml:"origin,omitempty"`
}

// CutoutsItemMask describes the cutouts schema.
type CutoutsItemMask struct {
	// Mask preset name
	Preset *string `yaml:"preset,omitempty"`
	// Horizontal offset of the mask within the opening
	OffsetX *float64 `yaml:"offset_x,omitempty"`
	// Vertical offset of the mask within the opening
	OffsetY *float64 `yaml:"offset_y,omitempty"`
	// Additional rotation applied to the mask within the opening (degrees)
	Rotation *float64 `yaml:"rotation,omitempty"`
}

func (x *CutoutsItem) ApplyDefaults() {
	if x.Coordinate == nil {
		v := "pcb"
		x.Coordinate = &v
	}
	if x.Origin == nil {
		v := "global"
		x.Origin = &v
	}
}

func (x *CutoutsItem) CustomValidate() error {
	// Module author can add custom validation here
	return nil
}

func (x *CutoutsItemMask) ApplyDefaults() {
}

func (x *CutoutsItemMask) CustomValidate() error {
	// Module author can add custom validation here
	return nil
}

// Decode converts []map[string]any into typed []CutoutsItem entries.
func Decode(items []map[string]any) ([]CutoutsItem, error) {
	typed := make([]CutoutsItem, len(items))
	for idx, raw := range items {
		label := decode.FormatLabel("cutouts", idx)
		item, err := decodeCutoutsItem(raw, label)
		if err != nil {
			return nil, err
		}
		typed[idx] = item
	}
	return typed, nil
}

func decodeCutoutsItem(m map[string]any, label string) (CutoutsItem, error) {

	faceVal, err := decode.GetString(m, "face", label)
	if err != nil {
		return CutoutsItem{}, err
	}

	fromFaceLeftVal, err := decode.GetFloat(m, "from_face_left", label)
	if err != nil {
		return CutoutsItem{}, err
	}

	fromFaceBottomVal, err := decode.GetOptionalFloat(m, "from_face_bottom", label)
	if err != nil {
		return CutoutsItem{}, err
	}

	fromFaceBackVal, err := decode.GetOptionalFloat(m, "from_face_back", label)
	if err != nil {
		return CutoutsItem{}, err
	}

	widthVal, err := decode.GetOptionalFloat(m, "width", label)
	if err != nil {
		return CutoutsItem{}, err
	}

	lengthVal, err := decode.GetOptionalFloat(m, "length", label)
	if err != nil {
		return CutoutsItem{}, err
	}

	radiusVal, err := decode.GetOptionalFloat(m, "radius", label)
	if err != nil {
		return CutoutsItem{}, err
	}

	shapeVal, err := decode.GetString(m, "shape", label)
	if err != nil {
		return CutoutsItem{}, err
	}

	depthVal, err := decode.GetOptionalFloat(m, "depth", label)
	if err != nil {
		return CutoutsItem{}, err
	}

	angleVal, err := decode.GetOptionalFloat(m, "angle", label)
	if err != nil {
		return CutoutsItem{}, err
	}

	polygonVal, err := decode.GetOptionalString(m, "polygon", label)
	if err != nil {
		return CutoutsItem{}, err
	}

	maskValRaw, err := decode.GetOptionalObject(m, "mask", label)
	if err != nil {
		return CutoutsItem{}, err
	}
	var maskVal *CutoutsItemMask
	if maskValRaw != nil {
		decoded, err := decodeCutoutsItemMask(maskValRaw, label+".mask")
		if err != nil {
			return CutoutsItem{}, err
		}
		maskVal = &decoded
	}

	coordinateVal, err := decode.GetOptionalString(m, "coordinate", label)
	if err != nil {
		return CutoutsItem{}, err
	}

	originVal, err := decode.GetOptionalString(m, "origin", label)
	if err != nil {
		return CutoutsItem{}, err
	}

	item := CutoutsItem{
		Face:           faceVal,
		FromFaceLeft:   fromFaceLeftVal,
		FromFaceBottom: fromFaceBottomVal,
		FromFaceBack:   fromFaceBackVal,
		Width:          widthVal,
		Length:         lengthVal,
		Radius:         radiusVal,
		Shape:          shapeVal,
		Depth:          depthVal,
		Angle:          angleVal,
		Polygon:        polygonVal,
		Mask:           maskVal,
		Coordinate:     coordinateVal,
		Origin:         originVal,
	}

	item.ApplyDefaults()
	if err := item.CustomValidate(); err != nil {
		return CutoutsItem{}, errors.Wrapf(err, "%s", label)
	}

	return item, nil
}

func decodeCutoutsItemMask(m map[string]any, label string) (CutoutsItemMask, error) {

	presetVal, err := decode.GetOptionalString(m, "preset", label)
	if err != nil {
		return CutoutsItemMask{}, err
	}

	offsetXVal, err := decode.GetOptionalFloat(m, "offset_x", label)
	if err != nil {
		return CutoutsItemMask{}, err
	}

	offsetYVal, err := decode.GetOptionalFloat(m, "offset_y", label)
	if err != nil {
		return CutoutsItemMask{}, err
	}

	rotationVal, err := decode.GetOptionalFloat(m, "rotation", label)
	if err != nil {
		return CutoutsItemMask{}, err
	}

	item := CutoutsItemMask{
		Preset:   presetVal,
		OffsetX:  offsetXVal,
		OffsetY:  offsetYVal,
		Rotation: rotationVal,
	}

	item.ApplyDefaults()
	if err := item.CustomValidate(); err != nil {
		return CutoutsItemMask{}, errors.Wrapf(err, "%s", label)
	}

	return item, nil
}
