// Code generated by schemagen; DO NOT EDIT.

package cutouts

// CutoutsItem describes the cutouts schema.
type CutoutsItem struct {
	// Which face of the enclosure
	Face string `yaml:"face"`
	// Distance from back edge (mm)
	FromBack float64 `yaml:"from_back"`
	// Distance from left edge (mm)
	FromLeft float64 `yaml:"from_left"`
	// Cutout width (set to 0 for circles)
	Width float64 `yaml:"width"`
	// Cutout length (set to 0 for circles)
	Length float64 `yaml:"length"`
	// Corner/circle radius (set to 0 for rectangles)
	Radius float64 `yaml:"radius"`
	// Cutout shape (maps to YAPP shape flag)
	Shape string `yaml:"shape"`
	// Cutout depth (defaults to shell thickness)
	Depth *float64 `yaml:"depth,omitempty"`
	// Rotation angle in degrees
	Angle *float64 `yaml:"angle,omitempty"`
	// Polygon preset shape name (required when shape=polygon). Options: hexagon, arrow, 6pt_star, iso_triangle, iso_triangle2, triangle, triangle2
	Polygon *string `yaml:"polygon,omitempty"`
}

func (x *CutoutsItem) ApplyDefaults() {
}

func (x *CutoutsItem) CustomValidate() error {
	// Module author can add custom validation here
	return nil
}
