// Code generated by schemagen; DO NOT EDIT.

package cutouts

import (
	"testing"

	"gopkg.in/yaml.v3"
)

func TestCutoutsItem_RectangleCutout(t *testing.T) {
	var item CutoutsItem
	input := []byte(`face: front
from_back: 10
from_left: 15
length: 10
radius: 0
shape: rectangle
width: 20
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestCutoutsItem_CircleCutout(t *testing.T) {
	var item CutoutsItem
	input := []byte(`face: back
from_back: 25
from_left: 20
length: 0
radius: 5
shape: circle
width: 0
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}
