// Code generated by schemagen; DO NOT EDIT.

package cutouts

// CutoutsItem describes the cutouts schema.
type CutoutsItem struct {
	// Which face of the enclosure
	Face string `yaml:"face"`
	// Horizontal position along the face from the left edge (mm). Used by all faces: base, lid, front, back, left, right.

	FromFaceLeft float64 `yaml:"from_face_left"`
	// Vertical position from the bottom edge of the face (mm). Required for side faces (front, back, left, right). Not valid for horizontal faces (base, lid).

	FromFaceBottom *float64 `yaml:"from_face_bottom,omitempty"`
	// Depth position from the back edge of the face (mm). Required for horizontal faces (base, lid). Not valid for side faces (front, back, left, right).

	FromFaceBack *float64 `yaml:"from_face_back,omitempty"`
	// Cutout width (set to 0 for circles)
	Width *float64 `yaml:"width,omitempty"`
	// Cutout length (set to 0 for circles)
	Length *float64 `yaml:"length,omitempty"`
	// Corner/circle radius (set to 0 for rectangles)
	Radius *float64 `yaml:"radius,omitempty"`
	// Cutout shape (maps to YAPP shape flag)
	Shape string `yaml:"shape"`
	// Cutout depth (defaults to shell thickness)
	Depth *float64 `yaml:"depth,omitempty"`
	// Rotation angle in degrees
	Angle *float64 `yaml:"angle,omitempty"`
	// Polygon preset shape name (required when shape=polygon). Options: hexagon, arrow, 6pt_star, iso_triangle, iso_triangle2, triangle, triangle2
	Polygon *string `yaml:"polygon,omitempty"`
	// Ventilation mask to apply to the cutout opening. Uses predefined patterns from YAPP: honeycomb, hex_circles, circles, squares, bars, offset_bars. Optionally adjust placement within the opening using offsets and rotation.

	Mask *CutoutsItemMask `yaml:"mask,omitempty"`
	// Coordinate system: pcb (yappCoordPCB, default), box (yappCoordBox), box_inside (yappCoordBoxInside)
	Coordinate *string `yaml:"coordinate,omitempty"`
	// Origin placement: global (yappOrigin/yappGlobalOrigin, default), center (yappCenter), alt (yappAltOrigin/yappLeftOrigin)
	Origin *string `yaml:"origin,omitempty"`
}

// CutoutsItemMask describes the cutouts schema.
type CutoutsItemMask struct {
	// Mask preset name
	Preset *string `yaml:"preset,omitempty"`
	// Horizontal offset of the mask within the opening
	OffsetX *float64 `yaml:"offset_x,omitempty"`
	// Vertical offset of the mask within the opening
	OffsetY *float64 `yaml:"offset_y,omitempty"`
	// Additional rotation applied to the mask within the opening (degrees)
	Rotation *float64 `yaml:"rotation,omitempty"`
}

func (x *CutoutsItem) ApplyDefaults() {
	if x.Coordinate == nil {
		v := "pcb"
		x.Coordinate = &v
	}
	if x.Origin == nil {
		v := "global"
		x.Origin = &v
	}
}

func (x *CutoutsItem) CustomValidate() error {
	// Module author can add custom validation here
	return nil
}

func (x *CutoutsItemMask) ApplyDefaults() {
}

func (x *CutoutsItemMask) CustomValidate() error {
	// Module author can add custom validation here
	return nil
}
