// Code generated by schemagen; DO NOT EDIT.

package cutouts

import (
	"testing"

	"gopkg.in/yaml.v3"
)

func TestCutoutsItem_RectangleCutoutSideFace(t *testing.T) {
	var item CutoutsItem
	input := []byte(`face: front
from_face_bottom: 15
from_face_left: 10
length: 10
radius: 0
shape: rectangle
width: 20
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestCutoutsItem_CircleCutoutSideFace(t *testing.T) {
	var item CutoutsItem
	input := []byte(`face: back
from_face_bottom: 20
from_face_left: 25
length: 0
radius: 5
shape: circle
width: 0
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestCutoutsItem_CutoutOnBase(t *testing.T) {
	var item CutoutsItem
	input := []byte(`face: base
from_face_back: 20
from_face_left: 15
length: 25
radius: 5
shape: rounded_rect
width: 25
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestCutoutsItem_PolygonHexagonBase(t *testing.T) {
	var item CutoutsItem
	input := []byte(`face: base
from_face_back: 15
from_face_left: 15
length: 25
polygon: hexagon
radius: 5
shape: polygon
width: 25
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestCutoutsItem_PolygonArrowLid(t *testing.T) {
	var item CutoutsItem
	input := []byte(`angle: 30
face: lid
from_face_back: 20
from_face_left: 10
length: 20
polygon: arrow
radius: 0
shape: polygon
width: 20
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestCutoutsItemDecodeValidInput(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`face: front
from_face_bottom: 15
from_face_left: 10
length: 10
radius: 0
shape: rectangle
width: 20
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	items, err := Decode([]map[string]any{raw})
	if err != nil {
		t.Fatalf("unexpected decode error: %v", err)
	}
	if len(items) != 1 {
		t.Fatalf("expected 1 item, got %d", len(items))
	}
}
func TestCutoutsItemDecodeMissingRequired(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`face: front
from_face_bottom: 15
from_face_left: 10
length: 10
radius: 0
shape: rectangle
width: 20
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	delete(raw, "face")
	if _, err := Decode([]map[string]any{raw}); err == nil {
		t.Fatalf("expected error for missing required field")
	}
}

func TestCutoutsItemDecodeWrongType(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`face: front
from_face_bottom: 15
from_face_left: 10
length: 10
radius: 0
shape: rectangle
width: 20
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	raw["face"] = map[string]any{"unexpected": "type"}
	if _, err := Decode([]map[string]any{raw}); err == nil {
		t.Fatalf("expected error for wrong type on required field")
	}
}
