package schemagen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// GenerateOptions controls schemagen output.
type GenerateOptions struct {
	RootDir    string
	ModulePath string
}

// GenerateCode writes Go sources for all schema documents.
func GenerateCode(docs []*SchemaDoc, opts GenerateOptions) error {
	if opts.RootDir == "" {
		opts.RootDir = "."
	}
	if opts.ModulePath == "" {
		return fmt.Errorf("module path is required for code generation")
	}
	for _, doc := range docs {
		if err := generateModuleCode(doc, opts.RootDir); err != nil {
			return err
		}
		if err := generateModuleTests(doc, opts.RootDir); err != nil {
			return err
		}
	}
	if err := generateModulesRegistry(docs, opts.RootDir, opts.ModulePath); err != nil {
		return err
	}
	return nil
}

func generateModuleCode(doc *SchemaDoc, root string) error {
	structs := buildStructDefs(doc)
	var buf bytes.Buffer
	buf.WriteString("// Code generated by schemagen; DO NOT EDIT.\n\n")
	buf.WriteString("package " + doc.GoPackage + "\n\n")
	for _, def := range structs {
		if def.Comment != "" {
			buf.WriteString("// " + def.Comment + "\n")
		}
		buf.WriteString("type " + def.Name + " struct {\n")
		for _, field := range def.Fields {
			if field.Comment != "" {
				buf.WriteString("\t// " + field.Comment + "\n")
			}
			buf.WriteString(fmt.Sprintf("\t%s %s %s\n", field.GoName, field.Type, backtick(field.Tag)))
		}
		buf.WriteString("}\n\n")
	}
	outPath := filepath.Join(resolveRoot(root, doc.ModuleDir()), "schema_gen.go")
	return writeGoFile(outPath, buf.Bytes())
}

func generateModuleTests(doc *SchemaDoc, root string) error {
	var positive []SchemaTest
	for _, test := range doc.Tests {
		if test.ExpectValid {
			positive = append(positive, test)
		}
	}
	if len(positive) == 0 {
		return nil
	}
	var buf bytes.Buffer
	buf.WriteString("// Code generated by schemagen; DO NOT EDIT.\n\n")
	buf.WriteString("package " + doc.GoPackage + "\n\n")
	buf.WriteString("import (\n\t\"testing\"\n\n\t\"gopkg.in/yaml.v3\"\n)\n\n")
	rootType := doc.RootStructName()
	for _, test := range positive {
		funcName := fmt.Sprintf("Test%s_%s", rootType, toCamel(test.Name))
		buf.WriteString(fmt.Sprintf("func %s(t *testing.T) {\n", funcName))
		buf.WriteString(fmt.Sprintf("\tvar item %s\n", rootType))
		if test.InputNode != nil {
			var val any
			if err := test.InputNode.Decode(&val); err != nil {
				continue
			}
			data, _ := yaml.Marshal(val)
			buf.WriteString("\tinput := []byte(`" + escapeBackticks(string(data)) + "`)\n")
			buf.WriteString("\tif err := yaml.Unmarshal(input, &item); err != nil {\n")
			buf.WriteString("\t\tt.Fatalf(\"unexpected error: %v\", err)\n\t}\n")
		} else {
			buf.WriteString("\tif err := yaml.Unmarshal([]byte(\"{}\"), &item); err != nil {\n")
			buf.WriteString("\t\tt.Fatalf(\"unexpected error: %v\", err)\n\t}\n")
		}
		buf.WriteString("}\n\n")
	}
	outPath := filepath.Join(resolveRoot(root, doc.ModuleDir()), "schema_gen_test.go")
	return writeGoFile(outPath, buf.Bytes())
}

func generateModulesRegistry(docs []*SchemaDoc, root, modulePath string) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by schemagen; DO NOT EDIT.\n\n")
	buf.WriteString("package yappgen\n\n")
	buf.WriteString("import (\n")
	buf.WriteString(fmt.Sprintf("\t\"%s/pkg/registry\"\n", modulePath))
	for _, doc := range docs {
		importPath := filepath.ToSlash(filepath.Join(modulePath, doc.ModuleDir()))
		buf.WriteString(fmt.Sprintf("\t%s \"%s\"\n", doc.GoPackage, importPath))
	}
	buf.WriteString(")\n\n")
	buf.WriteString("func init() {\n")
	for _, doc := range docs {
		buf.WriteString(fmt.Sprintf("\tregistry.Register(%s.NewModule())\n", doc.GoPackage))
	}
	buf.WriteString("}\n")
	outPath := filepath.Join(resolveRoot(root, filepath.Join("pkg", "yappgen")), "modules_gen.go")
	return writeGoFile(outPath, buf.Bytes())
}

type structFieldDef struct {
	GoName  string
	Type    string
	Tag     string
	Comment string
}

type structDef struct {
	Name    string
	Comment string
	Fields  []structFieldDef
}

func buildStructDefs(doc *SchemaDoc) []structDef {
	var defs []structDef
	queue := []struct {
		name   string
		fields []*SchemaField
	}{
		{name: doc.RootStructName(), fields: doc.Fields},
	}
	seen := map[string]bool{}
	for len(queue) > 0 {
		current := queue[0]
		queue = queue[1:]
		if seen[current.name] {
			continue
		}
		seen[current.name] = true
		def := structDef{
			Name:    current.name,
			Comment: fmt.Sprintf("%s describes the push_buttons schema.", current.name),
		}
		for _, f := range current.fields {
			goName := toCamel(f.Name)
			fieldType := scalarTypeForField(current.name, f)
			tag := fmt.Sprintf(`yaml:"%s`, f.Name)
			if !f.Required {
				tag += ",omitempty"
			}
			tag += `"`
			comment := f.Description
			if comment == "" {
				comment = fmt.Sprintf("%s field", f.Name)
			}
			def.Fields = append(def.Fields, structFieldDef{
				GoName:  goName,
				Type:    fieldType,
				Tag:     tag,
				Comment: comment,
			})
			if f.Type == "object" && len(f.Children) > 0 {
				childName := nestedStructName(current.name, f.Name)
				queue = append(queue, struct {
					name   string
					fields []*SchemaField
				}{name: childName, fields: f.Children})
			}
		}
		defs = append(defs, def)
	}
	return defs
}

func scalarTypeForField(parentName string, field *SchemaField) string {
	goType := ""
	switch field.Type {
	case "number":
		goType = "float64"
	case "string":
		goType = "string"
	case "bool":
		goType = "bool"
	case "object":
		goType = nestedStructName(parentName, field.Name)
	default:
		goType = "any"
	}
	if !field.Required {
		switch goType {
		case "float64":
			return "*float64"
		case "string":
			return "*string"
		case "bool":
			return "*bool"
		default:
			return "*" + goType
		}
	}
	return goType
}

func nestedStructName(parent, field string) string {
	return parent + toCamel(field)
}

func writeGoFile(path string, data []byte) error {
	formatted, err := format.Source(data)
	if err == nil {
		data = formatted
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

func backtick(value string) string {
	if value == "" {
		return ""
	}
	return "`" + value + "`"
}

func escapeBackticks(s string) string {
	return strings.ReplaceAll(s, "`", "` + \"`\" + `")
}

func resolveRoot(root, path string) string {
	if filepath.IsAbs(path) {
		return path
	}
	return filepath.Join(root, path)
}
