package yappgen

import (
	"context"
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/wesen/yapp-encl-resolver/pkg/yappgen/scad"
)

// EmitSCAD renders a complete SCAD file for YAPP based on the given model.
// It relies on YAPP defaults for coordinate systems; no explicit coord flags are emitted (MVP).
func EmitSCAD(ctx context.Context, m *Model) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Generated by yappgen (MVP)\n")
	b.WriteString("include <./YAPPgenerator_v3.scad>\n\n")

	if m.RawDocument != nil {
		writeYamlSection(&b, m.RawDocument, "pcb")
		writeYamlSection(&b, m.RawDocument, "vars")
		writeYamlSection(&b, m.RawDocument, "enclosure")
		b.WriteByte('\n')
	}

	if m.PrintSwitchExtenders {
		b.WriteString("printSwitchExtenders = true;\n")
	} else {
		b.WriteString("printSwitchExtenders = false;\n")
	}

	// Globals (subset)
	writeVarFloat(&b, "pcbLength", m.PcbLength, m.Provenance)
	writeVarFloat(&b, "pcbWidth", m.PcbWidth, m.Provenance)
	writeVarFloat(&b, "pcbThickness", m.PcbThickness, m.Provenance)
	writeVarFloat(&b, "standoffHeight", m.StandoffHeight, m.Provenance)
	if m.StandoffDiameter > 0 {
		writeVarFloat(&b, "standoffDiameter", m.StandoffDiameter, m.Provenance)
	}
	if m.StandoffPinDia > 0 {
		writeVarFloat(&b, "standoffPinDiameter", m.StandoffPinDia, m.Provenance)
	}
	if m.StandoffHoleSlack > 0 {
		writeVarFloat(&b, "standoffHoleSlack", m.StandoffHoleSlack, m.Provenance)
	}
	if m.WallThickness > 0 {
		writeVarFloat(&b, "wallThickness", m.WallThickness, m.Provenance)
	}
	if m.BasePlaneThickness > 0 {
		writeVarFloat(&b, "basePlaneThickness", m.BasePlaneThickness, m.Provenance)
	}
	if m.LidPlaneThickness > 0 {
		writeVarFloat(&b, "lidPlaneThickness", m.LidPlaneThickness, m.Provenance)
	}
	if m.BaseWallHeight > 0 {
		writeVarFloat(&b, "baseWallHeight", m.BaseWallHeight, m.Provenance)
	}
	if m.LidWallHeight > 0 {
		writeVarFloat(&b, "lidWallHeight", m.LidWallHeight, m.Provenance)
	}
	if m.RidgeHeight > 0 {
		writeVarFloat(&b, "ridgeHeight", m.RidgeHeight, m.Provenance)
	}
	if m.RoundRadius > 0 {
		writeVarFloat(&b, "roundRadius", m.RoundRadius, m.Provenance)
	}
	if m.PaddingFront > 0 {
		writeVarFloat(&b, "paddingFront", m.PaddingFront, m.Provenance)
	}
	if m.PaddingBack > 0 {
		writeVarFloat(&b, "paddingBack", m.PaddingBack, m.Provenance)
	}
	if m.PaddingLeft > 0 {
		writeVarFloat(&b, "paddingLeft", m.PaddingLeft, m.Provenance)
	}
	if m.PaddingRight > 0 {
		writeVarFloat(&b, "paddingRight", m.PaddingRight, m.Provenance)
	}
	b.WriteString("\n")

	// Features
	if err := emitFeatureModules(ctx, m, &b); err != nil {
		return nil, err
	}

	// Footer
	b.WriteString("\nYAPPgenerate();\n")
	return []byte(b.String()), nil
}

func writeVarFloat(b *strings.Builder, name string, val float64, prov *Provenance) {
	if prov != nil {
		for _, line := range prov.ScalarComment(name) {
			b.WriteString(line)
			b.WriteByte('\n')
		}
	}
	fmt.Fprintf(b, "%s = %s;\n", name, formatFloat(val))
}

func writeArrayDecl(b *strings.Builder, name string, rows [][]any, header []string, rowComments [][]string) {
	for _, line := range header {
		if strings.TrimSpace(line) == "" {
			continue
		}
		b.WriteString(line)
		b.WriteByte('\n')
	}
	b.WriteString(name)
	b.WriteString(" =\n[\n")
	for i, row := range rows {
		if len(rowComments) > i {
			for _, line := range rowComments[i] {
				if line == "" {
					continue
				}
				b.WriteString(line)
				b.WriteByte('\n')
			}
			if len(rowComments[i]) > 0 {
				b.WriteByte('\n')
			}
		}
		b.WriteString("  [")
		for j, v := range row {
			writeScadValue(b, v)
			if j < len(row)-1 {
				b.WriteString(", ")
			}
		}
		b.WriteString("]")
		if i < len(rows)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
		if i < len(rows)-1 {
			b.WriteByte('\n')
		}
	}
	b.WriteString("];\n")
}

func writeScadValue(b *strings.Builder, v any) {
	switch t := v.(type) {
	case scad.Raw:
		b.WriteString(string(t))
	case string:
		// strings are quoted; MVP rarely uses quoted strings in arrays
		fmt.Fprintf(b, "%q", t)
	case float64:
		b.WriteString(formatFloat(t))
	case float32:
		b.WriteString(formatFloat(float64(t)))
	case int:
		fmt.Fprintf(b, "%d", t)
	case int64:
		fmt.Fprintf(b, "%d", t)
	case []any:
		// Handle nested arrays (e.g., [yappPCBName, "Sensor"])
		b.WriteString("[")
		for i, elem := range t {
			writeScadValue(b, elem)
			if i < len(t)-1 {
				b.WriteString(", ")
			}
		}
		b.WriteString("]")
	default:
		// Fallback to fmt (should not happen)
		fmt.Fprintf(b, "%v", t)
	}
}

func formatFloat(v float64) string {
	// Emit minimal but precise numbers; trim trailing zeros when possible.
	s := fmt.Sprintf("%.6f", v)
	// trim trailing zeros and possible trailing dot
	s = strings.TrimRight(s, "0")
	if strings.HasSuffix(s, ".") {
		s = s[:len(s)-1]
	}
	if s == "" || s == "-" {
		return "0"
	}
	return s
}

func writeYamlSection(b *strings.Builder, raw map[string]any, key string) {
	if raw == nil {
		return
	}
	val, ok := raw[key]
	if !ok || val == nil {
		return
	}
	data, err := yaml.Marshal(map[string]any{key: val})
	if err != nil {
		return
	}
	content := strings.TrimRight(string(data), "\n")
	if content == "" {
		return
	}
	b.WriteString("// YAML ")
	b.WriteString(key)
	b.WriteString(":\n")
	for _, line := range strings.Split(content, "\n") {
		line = strings.TrimRight(line, "\r")
		b.WriteString("//   ")
		b.WriteString(line)
		b.WriteByte('\n')
	}
	b.WriteByte('\n')
}
