package yappgen

import (
    "context"
    "fmt"
    "strings"

    "github.com/wesen/yapp-encl-resolver/pkg/yappgen/scad"
)

// EmitSCAD renders a complete SCAD file for YAPP based on the given model.
// It relies on YAPP defaults for coordinate systems; no explicit coord flags are emitted (MVP).
func EmitSCAD(ctx context.Context, m *Model) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Generated by yappgen (MVP)\n")
	b.WriteString("include <./YAPPgenerator_v3.scad>\n\n")

	if m.PrintSwitchExtenders {
		b.WriteString("printSwitchExtenders = true;\n")
	} else {
		b.WriteString("printSwitchExtenders = false;\n")
	}

	// Globals (subset)
	writeVarFloat(&b, "pcbLength", m.PcbLength)
	writeVarFloat(&b, "pcbWidth", m.PcbWidth)
	writeVarFloat(&b, "pcbThickness", m.PcbThickness)
	writeVarFloat(&b, "standoffHeight", m.StandoffHeight)
	if m.StandoffDiameter > 0 {
		writeVarFloat(&b, "standoffDiameter", m.StandoffDiameter)
	}
	if m.StandoffPinDia > 0 {
		writeVarFloat(&b, "standoffPinDiameter", m.StandoffPinDia)
	}
	if m.StandoffHoleSlack > 0 {
		writeVarFloat(&b, "standoffHoleSlack", m.StandoffHoleSlack)
	}
	if m.WallThickness > 0 {
		writeVarFloat(&b, "wallThickness", m.WallThickness)
	}
	if m.BasePlaneThickness > 0 {
		writeVarFloat(&b, "basePlaneThickness", m.BasePlaneThickness)
	}
	if m.LidPlaneThickness > 0 {
		writeVarFloat(&b, "lidPlaneThickness", m.LidPlaneThickness)
	}
	if m.BaseWallHeight > 0 {
		writeVarFloat(&b, "baseWallHeight", m.BaseWallHeight)
	}
	if m.LidWallHeight > 0 {
		writeVarFloat(&b, "lidWallHeight", m.LidWallHeight)
	}
	if m.RidgeHeight > 0 {
		writeVarFloat(&b, "ridgeHeight", m.RidgeHeight)
	}
	if m.RoundRadius > 0 {
		writeVarFloat(&b, "roundRadius", m.RoundRadius)
	}
	if m.PaddingFront > 0 {
		writeVarFloat(&b, "paddingFront", m.PaddingFront)
	}
	if m.PaddingBack > 0 {
		writeVarFloat(&b, "paddingBack", m.PaddingBack)
	}
	if m.PaddingLeft > 0 {
		writeVarFloat(&b, "paddingLeft", m.PaddingLeft)
	}
	if m.PaddingRight > 0 {
		writeVarFloat(&b, "paddingRight", m.PaddingRight)
	}
	b.WriteString("\n")

	// Features
	if err := emitFeatureModules(ctx, m, &b); err != nil {
		return nil, err
	}

	// Footer
	b.WriteString("\nYAPPgenerate();\n")
	return []byte(b.String()), nil
}

func writeVarFloat(b *strings.Builder, name string, val float64) {
	fmt.Fprintf(b, "%s = %s;\n", name, formatFloat(val))
}

func writeArrayDecl(b *strings.Builder, name string, rows [][]any) {
	b.WriteString(name)
	b.WriteString(" =\n[\n")
	for i, row := range rows {
		b.WriteString("  [")
		for j, v := range row {
			writeScadValue(b, v)
			if j < len(row)-1 {
				b.WriteString(", ")
			}
		}
		b.WriteString("]")
		if i < len(rows)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString("];\n")
}

func writeScadValue(b *strings.Builder, v any) {
	switch t := v.(type) {
    case scad.Raw:
        b.WriteString(string(t))
	case string:
		// strings are quoted; MVP rarely uses quoted strings in arrays
		fmt.Fprintf(b, "%q", t)
	case float64:
		b.WriteString(formatFloat(t))
	case float32:
		b.WriteString(formatFloat(float64(t)))
	case int:
		fmt.Fprintf(b, "%d", t)
	case int64:
		fmt.Fprintf(b, "%d", t)
	case []any:
		// Handle nested arrays (e.g., [yappPCBName, "Sensor"])
		b.WriteString("[")
		for i, elem := range t {
			writeScadValue(b, elem)
			if i < len(t)-1 {
				b.WriteString(", ")
			}
		}
		b.WriteString("]")
	default:
		// Fallback to fmt (should not happen)
		fmt.Fprintf(b, "%v", t)
	}
}

func formatFloat(v float64) string {
	// Emit minimal but precise numbers; trim trailing zeros when possible.
	s := fmt.Sprintf("%.6f", v)
	// trim trailing zeros and possible trailing dot
	s = strings.TrimRight(s, "0")
	if strings.HasSuffix(s, ".") {
		s = s[:len(s)-1]
	}
	if s == "" || s == "-" {
		return "0"
	}
	return s
}
