package yappgen

import (
	"context"
	"fmt"
	"sort"
	"strings"
)

// EmitSCAD renders a complete SCAD file for YAPP based on the given model.
// It relies on YAPP defaults for coordinate systems; no explicit coord flags are emitted (MVP).
func EmitSCAD(ctx context.Context, m *Model) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Generated by yappgen (MVP)\n")
	b.WriteString("include <./YAPPgenerator_v3.scad>\n\n")

	// Globals (subset)
	writeVarFloat(&b, "pcbLength", m.PcbLength)
	writeVarFloat(&b, "pcbWidth", m.PcbWidth)
	writeVarFloat(&b, "pcbThickness", m.PcbThickness)
	writeVarFloat(&b, "standoffHeight", m.StandoffHeight)
	if m.StandoffDiameter > 0 {
		writeVarFloat(&b, "standoffDiameter", m.StandoffDiameter)
	}
	if m.StandoffPinDia > 0 {
		writeVarFloat(&b, "standoffPinDiameter", m.StandoffPinDia)
	}
	if m.StandoffHoleSlack > 0 {
		writeVarFloat(&b, "standoffHoleSlack", m.StandoffHoleSlack)
	}
	if m.WallThickness > 0 {
		writeVarFloat(&b, "wallThickness", m.WallThickness)
	}
	if m.BasePlaneThickness > 0 {
		writeVarFloat(&b, "basePlaneThickness", m.BasePlaneThickness)
	}
	if m.LidPlaneThickness > 0 {
		writeVarFloat(&b, "lidPlaneThickness", m.LidPlaneThickness)
	}
	if m.RoundRadius > 0 {
		writeVarFloat(&b, "roundRadius", m.RoundRadius)
	}
	if m.PaddingFront > 0 {
		writeVarFloat(&b, "paddingFront", m.PaddingFront)
	}
	if m.PaddingBack > 0 {
		writeVarFloat(&b, "paddingBack", m.PaddingBack)
	}
	if m.PaddingLeft > 0 {
		writeVarFloat(&b, "paddingLeft", m.PaddingLeft)
	}
	if m.PaddingRight > 0 {
		writeVarFloat(&b, "paddingRight", m.PaddingRight)
	}
	b.WriteString("\n")

	// Features
	// pcbStands
	if len(m.PcbStands) > 0 {
		list, err := buildPcbStands(m.PcbStands)
		if err != nil {
			return nil, err
		}
		writeArrayDecl(&b, "pcbStands", list)
		b.WriteString("\n")
	}
	// connectors
	if len(m.Connectors) > 0 {
		list, err := buildConnectors(m.Connectors)
		if err != nil {
			return nil, err
		}
		writeArrayDecl(&b, "connectors", list)
		b.WriteString("\n")
	}
	// snapJoins
	if len(m.SnapJoins) > 0 {
		list, err := buildSnapJoins(m.SnapJoins)
		if err != nil {
			return nil, err
		}
		writeArrayDecl(&b, "snapJoins", list)
		b.WriteString("\n")
	}
	// cutouts by face
	if len(m.Cutouts) > 0 {
		byFace, err := distributeCutouts(m.Cutouts)
		if err != nil {
			return nil, err
		}
		// deterministic face order
		keys := make([]string, 0, len(byFace))
		for k := range byFace {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			if len(byFace[k]) == 0 {
				continue
			}
			writeArrayDecl(&b, k, byFace[k])
			b.WriteString("\n")
		}
	}

	// Footer
	b.WriteString("\nYAPPgenerate();\n")
	return []byte(b.String()), nil
}

func writeVarFloat(b *strings.Builder, name string, val float64) {
	fmt.Fprintf(b, "%s = %s;\n", name, formatFloat(val))
}

func writeArrayDecl(b *strings.Builder, name string, rows [][]any) {
	b.WriteString(name)
	b.WriteString(" =\n[\n")
	for i, row := range rows {
		b.WriteString("  [")
		for j, v := range row {
			writeScadValue(b, v)
			if j < len(row)-1 {
				b.WriteString(", ")
			}
		}
		b.WriteString("]")
		if i < len(rows)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString("];\n")
}

func writeScadValue(b *strings.Builder, v any) {
	switch t := v.(type) {
	case ScadRaw:
		b.WriteString(string(t))
	case string:
		// strings are quoted; MVP rarely uses quoted strings in arrays
		fmt.Fprintf(b, "%q", t)
	case float64:
		b.WriteString(formatFloat(t))
	case float32:
		b.WriteString(formatFloat(float64(t)))
	case int:
		fmt.Fprintf(b, "%d", t)
	case int64:
		fmt.Fprintf(b, "%d", t)
	default:
		// Fallback to fmt (should not happen)
		fmt.Fprintf(b, "%v", t)
	}
}

func formatFloat(v float64) string {
	// Emit minimal but precise numbers; trim trailing zeros when possible.
	s := fmt.Sprintf("%.6f", v)
	// trim trailing zeros and possible trailing dot
	s = strings.TrimRight(s, "0")
	if strings.HasSuffix(s, ".") {
		s = s[:len(s)-1]
	}
	if s == "" || s == "-" {
		return "0"
	}
	return s
}


