// Code generated by schemagen; DO NOT EDIT.

package yappgen

import (
	"github.com/wesen/yapp-encl-resolver/pkg/registry"
	boxmounts "github.com/wesen/yapp-encl-resolver/pkg/yappgen/modules/boxmounts"
	connectors "github.com/wesen/yapp-encl-resolver/pkg/yappgen/modules/connectors"
	cutouts "github.com/wesen/yapp-encl-resolver/pkg/yappgen/modules/cutouts"
	lighttubes "github.com/wesen/yapp-encl-resolver/pkg/yappgen/modules/lighttubes"
	pcbstands "github.com/wesen/yapp-encl-resolver/pkg/yappgen/modules/pcbstands"
	pushbuttons "github.com/wesen/yapp-encl-resolver/pkg/yappgen/modules/pushbuttons"
	snapjoins "github.com/wesen/yapp-encl-resolver/pkg/yappgen/modules/snapjoins"
)

func init() {
	registry.Register(boxmounts.NewModule())
	registry.Register(connectors.NewModule())
	registry.Register(cutouts.NewModule())
	registry.Register(lighttubes.NewModule())
	registry.Register(pcbstands.NewModule())
	registry.Register(pushbuttons.NewModule())
	registry.Register(snapjoins.NewModule())
}
