// Code generated by schemagen; DO NOT EDIT.

package yappgen

import (
	"github.com/wesen/yapp-encl-resolver/pkg/registry"
	pushbuttons "github.com/wesen/yapp-encl-resolver/pkg/yappgen/modules/pushbuttons"
)

func init() {
	registry.Register(pushbuttons.NewModule())
}
