// Code generated by schemagen; DO NOT EDIT.

package lighttubes

import (
	"testing"

	"gopkg.in/yaml.v3"
)

func TestLightTubesItem_MinimalCircle(t *testing.T) {
	var item LightTubesItem
	input := []byte(`gap_above_pcb: 0.1
shape: circle
tube_length: 5
tube_wall: 1
tube_width: 6
x: 15
"y": 10
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestLightTubesItem_RectangleWithLens(t *testing.T) {
	var item LightTubesItem
	input := []byte(`gap_above_pcb: 0.1
lens_thickness: 0.5
shape: rectangle
tube_length: 1.5
tube_wall: 1
tube_width: 5
x: 15
"y": 30
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestLightTubesItem_WithAllFlags(t *testing.T) {
	var item LightTubesItem
	input := []byte(`coordinate: box
fillet_radius: 0.5
gap_above_pcb: 0.2
height: 10
lens_thickness: 1
no_fillet: true
origin: alt
pcb_name: Main
shape: circle
tube_length: 8
tube_wall: 0.8
tube_width: 4
x: 20
"y": 25
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}
