// Code generated by schemagen; DO NOT EDIT.

package lighttubes

import (
	"github.com/pkg/errors"

	"github.com/wesen/yapp-encl-resolver/pkg/yappgen/decode"
)

// LightTubesItem describes the light_tubes schema.
type LightTubesItem struct {
	// X coordinate position (mm)
	X float64 `yaml:"x"`
	// Y coordinate position (mm)
	Y float64 `yaml:"y"`
	// Length of the light tube (mm)
	TubeLength float64 `yaml:"tube_length"`
	// Width/diameter of the light tube (mm)
	TubeWidth float64 `yaml:"tube_width"`
	// Wall thickness of the tube (mm)
	TubeWall float64 `yaml:"tube_wall"`
	// Gap between PCB and bottom of tube (mm)
	GapAbovePcb float64 `yaml:"gap_above_pcb"`
	// Tube cross-section shape (yappCircle/yappRectangle)
	Shape string `yaml:"shape"`
	// Thickness of lid material left at top (0 = open hole, mm)
	LensThickness *float64 `yaml:"lens_thickness,omitempty"`
	// Height to top of PCB (defaults to standoffHeight+pcbThickness)
	Height *float64 `yaml:"height,omitempty"`
	// Fillet radius at base (0 = auto)
	FilletRadius *float64 `yaml:"fillet_radius,omitempty"`
	// Coordinate system selector (yappCoordPCB/yappCoordBox/yappCoordBoxInside)
	Coordinate *string `yaml:"coordinate,omitempty"`
	// Origin selector (yappGlobalOrigin/yappAltOrigin)
	Origin *string `yaml:"origin,omitempty"`
	// Disable automatic fillets (yappNoFillet)
	NoFillet *bool `yaml:"no_fillet,omitempty"`
	// Target PCB name for multi-board projects (emits [yappPCBName, value])
	PcbName *string `yaml:"pcb_name,omitempty"`
}

func (x *LightTubesItem) ApplyDefaults() {
	if x.LensThickness == nil {
		v := 0.0
		x.LensThickness = &v
	}
	if x.Coordinate == nil {
		v := "pcb"
		x.Coordinate = &v
	}
	if x.Origin == nil {
		v := "global"
		x.Origin = &v
	}
}

func (x *LightTubesItem) CustomValidate() error {
	// Module author can add custom validation here
	return nil
}

// Decode converts []map[string]any into typed []LightTubesItem entries.
func Decode(items []map[string]any) ([]LightTubesItem, error) {
	typed := make([]LightTubesItem, len(items))
	for idx, raw := range items {
		label := decode.FormatLabel("light_tubes", idx)
		item, err := decodeLightTubesItem(raw, label)
		if err != nil {
			return nil, err
		}
		typed[idx] = item
	}
	return typed, nil
}

func decodeLightTubesItem(m map[string]any, label string) (LightTubesItem, error) {

	xVal, err := decode.GetFloat(m, "x", label)
	if err != nil {
		return LightTubesItem{}, err
	}

	yVal, err := decode.GetFloat(m, "y", label)
	if err != nil {
		return LightTubesItem{}, err
	}

	tubeLengthVal, err := decode.GetFloat(m, "tube_length", label)
	if err != nil {
		return LightTubesItem{}, err
	}

	tubeWidthVal, err := decode.GetFloat(m, "tube_width", label)
	if err != nil {
		return LightTubesItem{}, err
	}

	tubeWallVal, err := decode.GetFloat(m, "tube_wall", label)
	if err != nil {
		return LightTubesItem{}, err
	}

	gapAbovePcbVal, err := decode.GetFloat(m, "gap_above_pcb", label)
	if err != nil {
		return LightTubesItem{}, err
	}

	shapeVal, err := decode.GetString(m, "shape", label)
	if err != nil {
		return LightTubesItem{}, err
	}

	lensThicknessVal, err := decode.GetOptionalFloat(m, "lens_thickness", label)
	if err != nil {
		return LightTubesItem{}, err
	}

	heightVal, err := decode.GetOptionalFloat(m, "height", label)
	if err != nil {
		return LightTubesItem{}, err
	}

	filletRadiusVal, err := decode.GetOptionalFloat(m, "fillet_radius", label)
	if err != nil {
		return LightTubesItem{}, err
	}

	coordinateVal, err := decode.GetOptionalString(m, "coordinate", label)
	if err != nil {
		return LightTubesItem{}, err
	}

	originVal, err := decode.GetOptionalString(m, "origin", label)
	if err != nil {
		return LightTubesItem{}, err
	}

	noFilletVal, err := decode.GetOptionalBool(m, "no_fillet", label)
	if err != nil {
		return LightTubesItem{}, err
	}

	pcbNameVal, err := decode.GetOptionalString(m, "pcb_name", label)
	if err != nil {
		return LightTubesItem{}, err
	}

	item := LightTubesItem{
		X:             xVal,
		Y:             yVal,
		TubeLength:    tubeLengthVal,
		TubeWidth:     tubeWidthVal,
		TubeWall:      tubeWallVal,
		GapAbovePcb:   gapAbovePcbVal,
		Shape:         shapeVal,
		LensThickness: lensThicknessVal,
		Height:        heightVal,
		FilletRadius:  filletRadiusVal,
		Coordinate:    coordinateVal,
		Origin:        originVal,
		NoFillet:      noFilletVal,
		PcbName:       pcbNameVal,
	}

	item.ApplyDefaults()
	if err := item.CustomValidate(); err != nil {
		return LightTubesItem{}, errors.Wrapf(err, "%s", label)
	}

	return item, nil
}
