// Code generated by schemagen; DO NOT EDIT.

package lighttubes

// LightTubesItem describes the light_tubes schema.
type LightTubesItem struct {
	// X coordinate position (mm)
	X float64 `yaml:"x"`
	// Y coordinate position (mm)
	Y float64 `yaml:"y"`
	// Length of the light tube (mm)
	TubeLength float64 `yaml:"tube_length"`
	// Width/diameter of the light tube (mm)
	TubeWidth float64 `yaml:"tube_width"`
	// Wall thickness of the tube (mm)
	TubeWall float64 `yaml:"tube_wall"`
	// Gap between PCB and bottom of tube (mm)
	GapAbovePcb float64 `yaml:"gap_above_pcb"`
	// Tube cross-section shape (yappCircle/yappRectangle)
	Shape string `yaml:"shape"`
	// Thickness of lid material left at top (0 = open hole, mm)
	LensThickness *float64 `yaml:"lens_thickness,omitempty"`
	// Height to top of PCB (defaults to standoffHeight+pcbThickness)
	Height *float64 `yaml:"height,omitempty"`
	// Fillet radius at base (0 = auto)
	FilletRadius *float64 `yaml:"fillet_radius,omitempty"`
	// Coordinate system selector (yappCoordPCB/yappCoordBox/yappCoordBoxInside)
	Coordinate *string `yaml:"coordinate,omitempty"`
	// Origin selector (yappGlobalOrigin/yappAltOrigin)
	Origin *string `yaml:"origin,omitempty"`
	// Disable automatic fillets (yappNoFillet)
	NoFillet *bool `yaml:"no_fillet,omitempty"`
	// Target PCB name for multi-board projects (emits [yappPCBName, value])
	PcbName *string `yaml:"pcb_name,omitempty"`
}

func (x *LightTubesItem) ApplyDefaults() {
	if x.LensThickness == nil {
		v := 0.0
		x.LensThickness = &v
	}
	if x.Coordinate == nil {
		v := "pcb"
		x.Coordinate = &v
	}
	if x.Origin == nil {
		v := "global"
		x.Origin = &v
	}
}

func (x *LightTubesItem) CustomValidate() error {
	// Module author can add custom validation here
	return nil
}
