// Code generated by schemagen; DO NOT EDIT.

package boxmounts

import (
	"testing"

	"gopkg.in/yaml.v3"
)

func TestBoxMountsItem_MinimalMount(t *testing.T) {
	var item BoxMountsItem
	input := []byte(`faces:
    left: true
height: 5
pos: 12
screw_d: 3
slot_width: 0
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestBoxMountsItem_CenteredBackMount(t *testing.T) {
	var item BoxMountsItem
	input := []byte(`alignment: center
faces:
    back: true
fillet_radius: 1
height: 8
no_fillet: true
origin: alt
pos: 20
screw_d: 3.5
shell_part: lid
slot_width: 4
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestBoxMountsItemDecodeValidInput(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`faces:
    left: true
height: 5
pos: 12
screw_d: 3
slot_width: 0
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	items, err := Decode([]map[string]any{raw})
	if err != nil {
		t.Fatalf("unexpected decode error: %v", err)
	}
	if len(items) != 1 {
		t.Fatalf("expected 1 item, got %d", len(items))
	}
}
func TestBoxMountsItemDecodeMissingRequired(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`faces:
    left: true
height: 5
pos: 12
screw_d: 3
slot_width: 0
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	delete(raw, "pos")
	if _, err := Decode([]map[string]any{raw}); err == nil {
		t.Fatalf("expected error for missing required field")
	}
}

func TestBoxMountsItemDecodeWrongType(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`faces:
    left: true
height: 5
pos: 12
screw_d: 3
slot_width: 0
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	raw["pos"] = map[string]any{"unexpected": "type"}
	if _, err := Decode([]map[string]any{raw}); err == nil {
		t.Fatalf("expected error for wrong type on required field")
	}
}
