// Code generated by schemagen; DO NOT EDIT.

package boxmounts

import (
	"github.com/pkg/errors"

	"github.com/wesen/yapp-encl-resolver/pkg/yappgen/decode"
)

// BoxMountsItem describes the box_mounts schema.
type BoxMountsItem struct {
	// Position along the selected wall (mm)
	Pos float64 `yaml:"pos"`
	// Secondary offset for angled/paired mounts (mm)
	Offset *float64 `yaml:"offset,omitempty"`
	// Screw diameter (mm)
	ScrewD float64 `yaml:"screw_d"`
	// Additional width beyond screw diameter (0 produces a circular hole)
	SlotWidth float64 `yaml:"slot_width"`
	// Mount height (mm) measured from base reference
	Height float64 `yaml:"height"`
	// Override fillet radius (0 = auto)
	FilletRadius *float64 `yaml:"fillet_radius,omitempty"`
	// Which shell is affected (maps to yappBase/yappLid flags)
	ShellPart *string `yaml:"shell_part,omitempty"`
	// Edge aligns to left of slot (edge) or centers (`yappCenter`)
	Alignment *string `yaml:"alignment,omitempty"`
	// Origin selector for back/right faces (`yappGlobalOrigin`/`yappAltOrigin`)
	Origin *string `yaml:"origin,omitempty"`
	// Disable automatic fillets (yappNoFillet)
	NoFillet *bool `yaml:"no_fillet,omitempty"`
	// Which enclosure walls receive this mount
	Faces BoxMountsItemFaces `yaml:"faces"`
}

// BoxMountsItemFaces describes the box_mounts schema.
type BoxMountsItemFaces struct {
	// Apply mount to left wall
	Left *bool `yaml:"left,omitempty"`
	// Apply mount to right wall
	Right *bool `yaml:"right,omitempty"`
	// Apply mount to front wall
	Front *bool `yaml:"front,omitempty"`
	// Apply mount to back wall
	Back *bool `yaml:"back,omitempty"`
}

func (x *BoxMountsItem) ApplyDefaults() {
	if x.ShellPart == nil {
		v := "base"
		x.ShellPart = &v
	}
	if x.Alignment == nil {
		v := "edge"
		x.Alignment = &v
	}
	if x.Origin == nil {
		v := "global"
		x.Origin = &v
	}
}

func (x *BoxMountsItem) CustomValidate() error {
	// Module author can add custom validation here
	return nil
}

func (x *BoxMountsItemFaces) ApplyDefaults() {
}

func (x *BoxMountsItemFaces) CustomValidate() error {
	// Module author can add custom validation here
	return nil
}

// Decode converts []map[string]any into typed []BoxMountsItem entries.
func Decode(items []map[string]any) ([]BoxMountsItem, error) {
	typed := make([]BoxMountsItem, len(items))
	for idx, raw := range items {
		label := decode.FormatLabel("box_mounts", idx)
		item, err := decodeBoxMountsItem(raw, label)
		if err != nil {
			return nil, err
		}
		typed[idx] = item
	}
	return typed, nil
}

func decodeBoxMountsItem(m map[string]any, label string) (BoxMountsItem, error) {

	posVal, err := decode.GetFloat(m, "pos", label)
	if err != nil {
		return BoxMountsItem{}, err
	}

	offsetVal, err := decode.GetOptionalFloat(m, "offset", label)
	if err != nil {
		return BoxMountsItem{}, err
	}

	screwDVal, err := decode.GetFloat(m, "screw_d", label)
	if err != nil {
		return BoxMountsItem{}, err
	}

	slotWidthVal, err := decode.GetFloat(m, "slot_width", label)
	if err != nil {
		return BoxMountsItem{}, err
	}

	heightVal, err := decode.GetFloat(m, "height", label)
	if err != nil {
		return BoxMountsItem{}, err
	}

	filletRadiusVal, err := decode.GetOptionalFloat(m, "fillet_radius", label)
	if err != nil {
		return BoxMountsItem{}, err
	}

	shellPartVal, err := decode.GetOptionalString(m, "shell_part", label)
	if err != nil {
		return BoxMountsItem{}, err
	}

	alignmentVal, err := decode.GetOptionalString(m, "alignment", label)
	if err != nil {
		return BoxMountsItem{}, err
	}

	originVal, err := decode.GetOptionalString(m, "origin", label)
	if err != nil {
		return BoxMountsItem{}, err
	}

	noFilletVal, err := decode.GetOptionalBool(m, "no_fillet", label)
	if err != nil {
		return BoxMountsItem{}, err
	}

	facesValRaw, err := decode.GetObject(m, "faces", label)
	if err != nil {
		return BoxMountsItem{}, err
	}
	facesVal, err := decodeBoxMountsItemFaces(facesValRaw, label+".faces")
	if err != nil {
		return BoxMountsItem{}, err
	}

	item := BoxMountsItem{
		Pos:          posVal,
		Offset:       offsetVal,
		ScrewD:       screwDVal,
		SlotWidth:    slotWidthVal,
		Height:       heightVal,
		FilletRadius: filletRadiusVal,
		ShellPart:    shellPartVal,
		Alignment:    alignmentVal,
		Origin:       originVal,
		NoFillet:     noFilletVal,
		Faces:        facesVal,
	}

	item.ApplyDefaults()
	if err := item.CustomValidate(); err != nil {
		return BoxMountsItem{}, errors.Wrapf(err, "%s", label)
	}

	return item, nil
}

func decodeBoxMountsItemFaces(m map[string]any, label string) (BoxMountsItemFaces, error) {

	leftVal, err := decode.GetOptionalBool(m, "left", label)
	if err != nil {
		return BoxMountsItemFaces{}, err
	}

	rightVal, err := decode.GetOptionalBool(m, "right", label)
	if err != nil {
		return BoxMountsItemFaces{}, err
	}

	frontVal, err := decode.GetOptionalBool(m, "front", label)
	if err != nil {
		return BoxMountsItemFaces{}, err
	}

	backVal, err := decode.GetOptionalBool(m, "back", label)
	if err != nil {
		return BoxMountsItemFaces{}, err
	}

	item := BoxMountsItemFaces{
		Left:  leftVal,
		Right: rightVal,
		Front: frontVal,
		Back:  backVal,
	}

	item.ApplyDefaults()
	if err := item.CustomValidate(); err != nil {
		return BoxMountsItemFaces{}, errors.Wrapf(err, "%s", label)
	}

	return item, nil
}
