// Code generated by schemagen; DO NOT EDIT.

package boxmounts

import (
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func TestBoxMountsItem_MinimalMount(t *testing.T) {
	var item BoxMountsItem
	input := []byte(`faces:
    left: true
height: 5
pos: 12
screw_d: 3
slot_width: 0
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestBoxMountsItem_CenteredBackMount(t *testing.T) {
	var item BoxMountsItem
	input := []byte(`alignment: center
faces:
    back: true
fillet_radius: 1
height: 8
no_fillet: true
origin: alt
pos: 20
screw_d: 3.5
shell_part: lid
slot_width: 4
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestBoxMountsItemDecodeValidInput(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`faces:
    left: true
height: 5
pos: 12
screw_d: 3
slot_width: 0
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	items, err := Decode([]map[string]any{raw})
	if err != nil {
		t.Fatalf("unexpected decode error: %v", err)
	}
	if len(items) != 1 {
		t.Fatalf("expected 1 item, got %d", len(items))
	}
}
func TestBoxMountsItemDecodeMissingRequired(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`faces:
    left: true
height: 5
pos: 12
screw_d: 3
slot_width: 0
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	delete(raw, "pos")
	if _, err := Decode([]map[string]any{raw}); err == nil {
		t.Fatalf("expected error for missing required field")
	}
}

func TestBoxMountsItemDecodeWrongType(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`faces:
    left: true
height: 5
pos: 12
screw_d: 3
slot_width: 0
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	raw["pos"] = "not a number"
	if _, err := Decode([]map[string]any{raw}); err == nil {
		t.Fatalf("expected error for wrong type on required field")
	}
}
func TestBuild_UsesGeneratedDecode(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`faces:
    left: true
height: 5
pos: 12
screw_d: 3
slot_width: 0
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	raw["pos"] = "not a number"
	if _, err := NewModule().Build([]map[string]any{raw}); err == nil {
		t.Fatalf("expected error when Build receives invalid field types")
	} else if !strings.Contains(err.Error(), "box_mounts[0].pos") {
		t.Fatalf("expected generated Decode error, got: %v", err)
	}
}

func TestBuild_ReturnsArrayDecl(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`faces:
    left: true
height: 5
pos: 12
screw_d: 3
slot_width: 0
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	decls, err := NewModule().Build([]map[string]any{raw})
	if err != nil {
		t.Fatalf("Build returned error: %v", err)
	}
	if len(decls) == 0 {
		t.Fatalf("expected Build to return at least 1 ArrayDecl")
	}
	if decls[0].Name == "" {
		t.Fatalf("expected ArrayDecl name to be set")
	}
	if !strings.HasPrefix(decls[0].Name, "boxMounts") {
		t.Fatalf("expected ArrayDecl name to start with boxMounts, got %s", decls[0].Name)
	}
	if len(decls[0].Rows) == 0 {
		t.Fatalf("expected ArrayDecl rows to contain data")
	}
}
