// Code generated by schemagen; DO NOT EDIT.
package boxmounts

import (
	"fmt"
	"github.com/pkg/errors"
)

type _svFieldSpec struct {
	Name     string
	Type     string
	Required bool
	ItemType string
	Children []_svFieldSpec
}

var _svSpecs = []_svFieldSpec{
	{Name: "pos", Type: "number", Required: true, Children: []_svFieldSpec{}},
	{Name: "offset", Type: "number", Required: false, Children: []_svFieldSpec{}},
	{Name: "screw_d", Type: "number", Required: true, Children: []_svFieldSpec{}},
	{Name: "slot_width", Type: "number", Required: true, Children: []_svFieldSpec{}},
	{Name: "height", Type: "number", Required: true, Children: []_svFieldSpec{}},
	{Name: "fillet_radius", Type: "number", Required: false, Children: []_svFieldSpec{}},
	{Name: "shell_part", Type: "string", Required: false, Children: []_svFieldSpec{}},
	{Name: "alignment", Type: "string", Required: false, Children: []_svFieldSpec{}},
	{Name: "origin", Type: "string", Required: false, Children: []_svFieldSpec{}},
	{Name: "no_fillet", Type: "bool", Required: false, Children: []_svFieldSpec{}},
	{Name: "faces", Type: "object", Required: true, Children: []_svFieldSpec{
		{Name: "left", Type: "bool", Required: false, Children: []_svFieldSpec{}},
		{Name: "right", Type: "bool", Required: false, Children: []_svFieldSpec{}},
		{Name: "front", Type: "bool", Required: false, Children: []_svFieldSpec{}},
		{Name: "back", Type: "bool", Required: false, Children: []_svFieldSpec{}},
	}},
}

// --- helpers ---
func _svHas(m map[string]any, k string) bool { _, ok := m[k]; return ok }
func _svIsString(v any) bool                 { _, ok := v.(string); return ok }
func _svIsBool(v any) bool                   { _, ok := v.(bool); return ok }
func _svIsNumberLike(v any) bool {
	switch v.(type) {
	case int, int64, float32, float64, string:
		return true
	default:
		return false
	}
}

func _svExpectNumberLike(m map[string]any, k, fp string) error {
	v, ok := m[k]
	if !ok {
		return errors.Errorf("%s: missing required field", fp)
	}
	if !_svIsNumberLike(v) {
		return errors.Errorf("%s: expected number|string", fp)
	}
	return nil
}

func _svFieldPath(base string, idx int, parent, field string) string {
	if parent == "" {
		return fmt.Sprintf("%s[%d].%s", base, idx, field)
	}
	return fmt.Sprintf("%s[%d].%s.%s", base, idx, parent, field)
}

func _svValidateObject(base string, idx int, parent string, m map[string]any, specs []_svFieldSpec) error {
	for _, f := range specs {
		fp := _svFieldPath(base, idx, parent, f.Name)
		v, present := m[f.Name]
		if !present {
			if f.Required {
				return errors.Errorf("%s: missing required field", fp)
			}
			continue
		}
		switch f.Type {
		case "string":
			if !_svIsString(v) {
				return errors.Errorf("%s: expected string", fp)
			}
		case "bool":
			if !_svIsBool(v) {
				return errors.Errorf("%s: expected bool", fp)
			}
		case "number":
			if !_svIsNumberLike(v) {
				return errors.Errorf("%s: expected number|string", fp)
			}
		case "object":
			mm, ok := v.(map[string]any)
			if !ok {
				return errors.Errorf("%s: expected object", fp)
			}
			if len(f.Children) > 0 {
				if err := _svValidateObject(base, idx, _svJoin(parent, f.Name), mm, f.Children); err != nil {
					return err
				}
			}
		case "array":
			arr, ok := v.([]any)
			if !ok {
				return errors.Errorf("%s: expected array", fp)
			}
			// Item kind checks when item type is provided
			if f.ItemType != "" {
				for i, ev := range arr {
					itemFp := fmt.Sprintf("%s[%d]", fp, i)
					switch f.ItemType {
					case "string":
						if !_svIsString(ev) {
							return errors.Errorf("%s: expected string", itemFp)
						}
					case "bool":
						if !_svIsBool(ev) {
							return errors.Errorf("%s: expected bool", itemFp)
						}
					case "number":
						if !_svIsNumberLike(ev) {
							return errors.Errorf("%s: expected number|string", itemFp)
						}
					case "object":
						mm, ok := ev.(map[string]any)
						if !ok {
							return errors.Errorf("%s: expected object", itemFp)
						}
						if len(f.Children) > 0 {
							if err := _svValidateObject(base, idx, _svJoin(parent, f.Name), mm, f.Children); err != nil {
								return err
							}
						}
					}
				}
			}
		default:
			// Unknown or unsupported types ignored for structure phase
		}
	}
	return nil
}

func _svJoin(parent, child string) string {
	if parent == "" {
		return child
	}
	return parent + "." + child
}

// _svValidateStructureImpl validates structure for this module (generated).
func _svValidateStructureImpl(path string, data any) error {
	if data == nil {
		return nil
	}
	arr, ok := data.([]any)
	if !ok {
		return errors.Errorf("%s: expected array", path)
	}
	for i, raw := range arr {
		item, ok := raw.(map[string]any)
		if !ok {
			return errors.Errorf("%s[%d]: expected object", path, i)
		}
		if err := _svValidateObject(path, i, "", item, _svSpecs); err != nil {
			return err
		}
	}
	return nil
}
