// Code generated by schemagen; DO NOT EDIT.

package boxmounts

import (
	"testing"

	"gopkg.in/yaml.v3"
)

func TestBoxMountsItem_MinimalMount(t *testing.T) {
	var item BoxMountsItem
	input := []byte(`faces:
    left: true
height: 5
pos: 12
screw_d: 3
slot_width: 0
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestBoxMountsItem_CenteredBackMount(t *testing.T) {
	var item BoxMountsItem
	input := []byte(`alignment: center
faces:
    back: true
fillet_radius: 1
height: 8
no_fillet: true
origin: alt
pos: 20
screw_d: 3.5
shell_part: lid
slot_width: 4
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}
