// Code generated by schemagen; DO NOT EDIT.

package boxmounts

// BoxMountsItem describes the box_mounts schema.
type BoxMountsItem struct {
	// Position along the selected wall (mm)
	Pos float64 `yaml:"pos"`
	// Secondary offset for angled/paired mounts (mm)
	Offset *float64 `yaml:"offset,omitempty"`
	// Screw diameter (mm)
	ScrewD float64 `yaml:"screw_d"`
	// Additional width beyond screw diameter (0 produces a circular hole)
	SlotWidth float64 `yaml:"slot_width"`
	// Mount height (mm) measured from base reference
	Height float64 `yaml:"height"`
	// Override fillet radius (0 = auto)
	FilletRadius *float64 `yaml:"fillet_radius,omitempty"`
	// Which shell is affected (maps to yappBase/yappLid flags)
	ShellPart *string `yaml:"shell_part,omitempty"`
	// Edge aligns to left of slot (edge) or centers (`yappCenter`)
	Alignment *string `yaml:"alignment,omitempty"`
	// Origin selector for back/right faces (`yappGlobalOrigin`/`yappAltOrigin`)
	Origin *string `yaml:"origin,omitempty"`
	// Disable automatic fillets (yappNoFillet)
	NoFillet *bool `yaml:"no_fillet,omitempty"`
	// Which enclosure walls receive this mount
	Faces BoxMountsItemFaces `yaml:"faces"`
}

// BoxMountsItemFaces describes the box_mounts schema.
type BoxMountsItemFaces struct {
	// Apply mount to left wall
	Left *bool `yaml:"left,omitempty"`
	// Apply mount to right wall
	Right *bool `yaml:"right,omitempty"`
	// Apply mount to front wall
	Front *bool `yaml:"front,omitempty"`
	// Apply mount to back wall
	Back *bool `yaml:"back,omitempty"`
}

func (x *BoxMountsItem) ApplyDefaults() {
	if x.ShellPart == nil {
		v := "base"
		x.ShellPart = &v
	}
	if x.Alignment == nil {
		v := "edge"
		x.Alignment = &v
	}
	if x.Origin == nil {
		v := "global"
		x.Origin = &v
	}
}

func (x *BoxMountsItem) CustomValidate() error {
	// Module author can add custom validation here
	return nil
}

func (x *BoxMountsItemFaces) ApplyDefaults() {
}

func (x *BoxMountsItemFaces) CustomValidate() error {
	// Module author can add custom validation here
	return nil
}
