// Generated by yappgen (MVP)
include <../YAPPgenerator_v3.scad>

printSwitchExtenders = true;
pcbLength = 100;
pcbWidth = 100;
pcbThickness = 1.6;
standoffHeight = 3;
standoffDiameter = 6;
standoffPinDiameter = 2.4;
standoffHoleSlack = 0.4;
wallThickness = 1.4;
basePlaneThickness = 1.5;
lidPlaneThickness = 1;
roundRadius = 2;
paddingFront = 1;
paddingBack = 1;
paddingLeft = 1;
paddingRight = 1;

pushButtons =
[
  [20, 50, 8, 8, 4, 0, 5, 0.5, 3, undef, yappCircle, undef, undef, undef, undef, undef, undef, yappNoFillet],
  [20, 30, 8, 8, 4, 0, 5, 0.5, 3, undef, yappCircle, 0, undef, 2, 2.5, 0.5, undef],
  [40, 50, 8, 8, 4, 0, 5, 0.5, 3, undef, yappPolygon, undef, undef, undef, undef, undef, undef, shapeArrow],
  [40, 30, 8, 8, 4, 0, 5, 0.5, 3, undef, yappPolygon, 90, undef, undef, undef, undef, undef, shapeArrow],
  [60, 50, 8, 8, 2, -1, 6, 1, 3, undef, yappRoundedRect, undef, undef, undef, undef, undef, undef],
  [80, 50, 8, 8, 0, 1, 5, 0.5, 3, undef, yappRectangle, 0, undef, undef, undef, undef, undef]
];


YAPPgenerate();
