// Generated by yappgen (MVP)
include <../YAPPgenerator_v3.scad>

printSwitchExtenders = true;
pcbLength = 30;
pcbWidth = 40;
pcbThickness = 1.6;
standoffHeight = 3;
standoffDiameter = 6;
standoffPinDiameter = 2.4;
standoffHoleSlack = 0.4;
wallThickness = 2.4;
basePlaneThickness = 1.6;
lidPlaneThickness = 1.6;
roundRadius = 2;
paddingFront = 1;
paddingBack = 1;
paddingLeft = 1;
paddingRight = 1;

pcbStands =
[
  [5, 5, undef, undef, undef, undef, undef, undef, undef],
  [25, 5, undef, undef, undef, undef, undef, undef, undef],
  [5, 35, undef, undef, undef, undef, undef, undef, undef],
  [25, 35, undef, undef, undef, undef, undef, undef, undef]
];

pushButtons =
[
  [15, 14, 8, 6, 0, 3, 5.5, 1, 3.5, undef, yappRectangle, undef, undef, undef, undef, undef, undef],
  [15, 28, 8, 8, 4, 0, 3, 1, 3.5, undef, yappCircle, undef, undef, undef, undef, 0.25, 0.2]
];


YAPPgenerate();
