// Generated by yappgen (MVP)
include <YAPPgenerator_v3.scad>

// YAML pcb:
//   pcb:
//       length: 50
//       thickness: 1.6
//       width: 30
//       z_clearance: 4

// YAML vars:
//   vars:
//       standoff_offset: 5
//       usb_center_x: pcb.length - 10.0
//       usb_center_y: pcb.width / 2
//       usb_height: 5
//       usb_width: 12

// YAML enclosure:
//   enclosure:
//       base:
//           thickness: 2
//           wall_height: pcb.z_clearance + 3.0
//       lid:
//           thickness: 2
//           wall_height: 25
//       wall:
//           clearance: 1.2
//           thickness: 2.2


printSwitchExtenders = false;
// long edge dimension
// pcbLength (source: pcb.length) = 50 (literal)
pcbLength = 50;
// pcbWidth (source: pcb.width) = 30 (literal)
pcbWidth = 30;
// pcbThickness (source: pcb.thickness) = 1.6 (literal)
pcbThickness = 1.6;
// standoffHeight (source: pcb.z_clearance) = 4 (literal)
standoffHeight = 4;
// standoffHoleSlack (source: tolerances.holes) = 0.3 (literal)
standoffHoleSlack = 0.3;
// wallThickness (source: enclosure.wall.thickness) = 2.2 (literal)
wallThickness = 2.2;
// basePlaneThickness (source: enclosure.base.thickness) = 2 (literal)
basePlaneThickness = 2;
// lidPlaneThickness (source: enclosure.lid.thickness) = 2 (literal)
lidPlaneThickness = 2;
// baseWallHeight (source: enclosure.base.wall_height) expr="pcb.z_clearance + 3.0" => 7 deps: pcb.z_clearance=4
baseWallHeight = 7;
// lidWallHeight (source: enclosure.lid.wall_height) = 25 (literal)
lidWallHeight = 25;
// paddingFront (source: enclosure.wall.clearance) = 1.2 (literal)
paddingFront = 1.2;
// paddingBack (source: enclosure.wall.clearance) = 1.2 (literal)
paddingBack = 1.2;
// paddingLeft (source: enclosure.wall.clearance) = 1.2 (literal)
paddingLeft = 1.2;
// paddingRight (source: enclosure.wall.clearance) = 1.2 (literal)
paddingRight = 1.2;

// YAPP pcbStands row: [x, y, height?, pcb_gap?, diameter?, pin_diameter?, hole_slack?, fillet_radius?, pin_length?]
pcbStands =
[
// YAML features.pcb_stands[0]:
//   diameter: 5
//   pin_diameter: 2.5
//   x: vars.standoff_offset
//   "y": vars.standoff_offset
// pcbStands[0] ← features.pcb_stands[0]
  // diameter (source: features.pcb_stands[0].diameter) = 5 (literal)
  // pin_diameter (source: features.pcb_stands[0].pin_diameter) = 2.5 (literal)
  // x (source: features.pcb_stands[0].x) expr="vars.standoff_offset" => 5 deps: vars.standoff_offset=5 (distance from corners)
  // y (source: features.pcb_stands[0].y) expr="vars.standoff_offset" => 5 deps: vars.standoff_offset=5 (distance from corners)

  [5, 5, undef, undef, 5, 2.5, undef, undef, undef],

// YAML features.pcb_stands[1]:
//   diameter: 5
//   pin_diameter: 2.5
//   x: pcb.length - vars.standoff_offset
//   "y": pcb.width - vars.standoff_offset
// pcbStands[1] ← features.pcb_stands[1]
  // diameter (source: features.pcb_stands[1].diameter) = 5 (literal)
  // pin_diameter (source: features.pcb_stands[1].pin_diameter) = 2.5 (literal)
  // x (source: features.pcb_stands[1].x) expr="pcb.length - vars.standoff_offset" => 45 deps: pcb.length=50 (long edge dimension), vars.standoff_offset=5 (distance from corners)
  // y (source: features.pcb_stands[1].y) expr="pcb.width - vars.standoff_offset" => 25 deps: pcb.width=30, vars.standoff_offset=5 (distance from corners)

  [45, 25, undef, undef, 5, 2.5, undef, undef, undef]
];

// YAPP cutouts row: [pos0, pos1, width, length, radius, shape_flag, depth?, angle?, extras...]
// Extras may include polygon presets, mask definitions, coordinate/origin flags, yappNoFillet, [yappPCBName, pcb_name].
cutoutsFront =
[
// YAML features.cutouts[0]:
//   face: front
//   from_face_bottom: enclosure.wall.clearance + enclosure.wall.thickness + vars.usb_center_y
//   from_face_left: enclosure.wall.clearance + enclosure.wall.thickness + vars.usb_center_x
//   length: vars.usb_height
//   name: usb-cutout
//   radius: 1
//   shape: rectangle
//   width: vars.usb_width
// cutoutsFront[0] ← features.cutouts[0]
  // face (source: features.cutouts[0].face) = "front" (literal "front")
  // from_face_bottom (source: features.cutouts[0].from_face_bottom) expr="enclosure.wall.clearance + enclosure.wall.thickness + vars.usb_center_y" => 18.4 deps: enclosure.wall.clearance=1.2, enclosure.wall.thickness=2.2, vars.usb_center_y=15 (centered vertically)
  // from_face_left (source: features.cutouts[0].from_face_left) expr="enclosure.wall.clearance + enclosure.wall.thickness + vars.usb_center_x" => 43.4 deps: enclosure.wall.clearance=1.2, enclosure.wall.thickness=2.2, vars.usb_center_x=40 (USB toward right edge)
  // length (source: features.cutouts[0].length) expr="vars.usb_height" => 5 deps: vars.usb_height=5
  // name (source: features.cutouts[0].name) = "usb-cutout" (literal "usb-cutout")
  // radius (source: features.cutouts[0].radius) = 1 (literal)
  // shape (source: features.cutouts[0].shape) = "rectangle" (literal "rectangle")
  // width (source: features.cutouts[0].width) expr="vars.usb_width" => 12 deps: vars.usb_width=12

  [43.4, 18.4, 12, 5, 0, yappRectangle, undef, undef]
];


YAPPgenerate();
