// Generated by yappgen (MVP)
include <YAPPgenerator_v3.scad>

printSwitchExtenders = false;
// long edge dimension
// pcbLength (source: pcb.length) = 50 (literal)
pcbLength = 50;
// pcbWidth (source: pcb.width) = 30 (literal)
pcbWidth = 30;
// pcbThickness (source: pcb.thickness) = 1.6 (literal)
pcbThickness = 1.6;
// standoffHeight (source: pcb.z_clearance) = 4 (literal)
standoffHeight = 4;
// standoffHoleSlack (source: tolerances.holes) = 0.3 (literal)
standoffHoleSlack = 0.3;
// wallThickness (source: enclosure.wall.thickness) = 2.2 (literal)
wallThickness = 2.2;
// basePlaneThickness (source: enclosure.base.thickness) = 2 (literal)
basePlaneThickness = 2;
// lidPlaneThickness (source: enclosure.lid.thickness) = 2 (literal)
lidPlaneThickness = 2;
// baseWallHeight (source: enclosure.base.wall_height) expr="pcb.z_clearance + 3.0" => 7 deps: pcb.z_clearance=4
baseWallHeight = 7;
// lidWallHeight (source: enclosure.lid.wall_height) = 25 (literal)
lidWallHeight = 25;
// paddingFront (source: enclosure.wall.clearance) = 1.2 (literal)
paddingFront = 1.2;
// paddingBack (source: enclosure.wall.clearance) = 1.2 (literal)
paddingBack = 1.2;
// paddingLeft (source: enclosure.wall.clearance) = 1.2 (literal)
paddingLeft = 1.2;
// paddingRight (source: enclosure.wall.clearance) = 1.2 (literal)
paddingRight = 1.2;

pcbStands =
[
// pcbStands[0] ← features.pcb_stands[0]
  // diameter (source: features.pcb_stands[0].diameter) = 5 (literal)
  // pin_diameter (source: features.pcb_stands[0].pin_diameter) = 2.5 (literal)
  // x (source: features.pcb_stands[0].x) expr="vars.standoff_offset" => 5 deps: vars.standoff_offset=5 (distance from corners)
  // y (source: features.pcb_stands[0].y) expr="vars.standoff_offset" => 5 deps: vars.standoff_offset=5 (distance from corners)
  [5, 5, undef, undef, 5, 2.5, undef, undef, undef],
// pcbStands[1] ← features.pcb_stands[1]
  // diameter (source: features.pcb_stands[1].diameter) = 5 (literal)
  // pin_diameter (source: features.pcb_stands[1].pin_diameter) = 2.5 (literal)
  // x (source: features.pcb_stands[1].x) expr="pcb.length - vars.standoff_offset" => 45 deps: pcb.length=50 (long edge dimension), vars.standoff_offset=5 (distance from corners)
  // y (source: features.pcb_stands[1].y) expr="pcb.width - vars.standoff_offset" => 25 deps: pcb.width=30, vars.standoff_offset=5 (distance from corners)
  [45, 25, undef, undef, 5, 2.5, undef, undef, undef]
];

cutoutsFront =
[
  [43.4, 18.4, 12, 5, 0, yappRectangle, undef, undef]
];


YAPPgenerate();
