// Generated by yappgen (MVP)
include <YAPPgenerator_v3.scad>

printSwitchExtenders = true;
// body length
// pcbLength (source: pcb.length) = 60 (literal)
pcbLength = 60;
// body width
// pcbWidth (source: pcb.width) = 35 (literal)
pcbWidth = 35;
// standard FR4
// pcbThickness (source: pcb.thickness) = 1.6 (literal)
pcbThickness = 1.6;
// standoff height target
// standoffHeight (source: pcb.z_clearance) = 3 (literal)
standoffHeight = 3;
// standoffHoleSlack (source: tolerances.holes) = 0.35 (literal)
standoffHoleSlack = 0.35;
// wallThickness (source: enclosure.wall.thickness) = 2.4 (literal)
wallThickness = 2.4;
// basePlaneThickness (source: enclosure.base.thickness) = 2 (literal)
basePlaneThickness = 2;
// lidPlaneThickness (source: enclosure.lid.thickness) = 2 (literal)
lidPlaneThickness = 2;
// baseWallHeight (source: enclosure.base.wall_height) expr="pcb.z_clearance + pcb.thickness + 4.0" => 8.6 deps: pcb.z_clearance=3 (standoff height target), pcb.thickness=1.6 (standard FR4)
baseWallHeight = 8.6;
// lidWallHeight (source: enclosure.lid.wall_height) = 35 (literal)
lidWallHeight = 35;
// paddingFront (source: enclosure.wall.clearance) = 1.5 (literal)
paddingFront = 1.5;
// paddingBack (source: enclosure.wall.clearance) = 1.5 (literal)
paddingBack = 1.5;
// paddingLeft (source: enclosure.wall.clearance) = 1.5 (literal)
paddingLeft = 1.5;
// paddingRight (source: enclosure.wall.clearance) = 1.5 (literal)
paddingRight = 1.5;

pushButtons =
[
// pushButtons[0] ← features.push_buttons[0]
  // cap.length (source: features.push_buttons[0].cap.length) expr="vars.cap_size" => 20 deps: vars.cap_size=20 (square cap)
  // cap.radius (source: features.push_buttons[0].cap.radius) expr="vars.cap_radius" => 10 deps: vars.cap_radius=10 (convert to radius)
  // cap.width (source: features.push_buttons[0].cap.width) expr="vars.cap_size" => 20 deps: vars.cap_size=20 (square cap)
  // lid.plate_thickness (source: features.push_buttons[0].lid.plate_thickness) = 2 (literal)
  // lid.protrusion (source: features.push_buttons[0].lid.protrusion) = 0 (literal)
  // lid.slack (source: features.push_buttons[0].lid.slack) = 0.3 (literal)
  // lid.snap_slack (source: features.push_buttons[0].lid.snap_slack) = 0.15 (literal)
  // lid.wall (source: features.push_buttons[0].lid.wall) = 1.8 (literal)
  // name (source: features.push_buttons[0].name) = "btn-left" (literal "btn-left")
  // shape (source: features.push_buttons[0].shape) = "circle" (literal "circle")
  // switch.height (source: features.push_buttons[0].switch.height) expr="vars.stack_height" => 15.5 deps: vars.stack_height=15.5 (switch stack height)
  // switch.pole_diameter (source: features.push_buttons[0].switch.pole_diameter) = 3 (literal)
  // switch.travel (source: features.push_buttons[0].switch.travel) = 0.8 (literal)
  // x (source: features.push_buttons[0].x) expr="vars.button_center - vars.button_spacing" => 14 deps: vars.button_center=30 (align row to center), vars.button_spacing=16 (distance center-to-center)
  // y (source: features.push_buttons[0].y) expr="vars.button_row_y" => 25 deps: vars.button_row_y=25 (keep buttons toward top edge)
  [14, 25, 20, 20, 10, 0, 15.5, 0.8, 3, undef, yappCircle, undef, undef, 1.8, 2, 0.3, 0.15],
// pushButtons[1] ← features.push_buttons[1]
  // cap.length (source: features.push_buttons[1].cap.length) expr="vars.cap_size" => 20 deps: vars.cap_size=20 (square cap)
  // cap.radius (source: features.push_buttons[1].cap.radius) expr="vars.cap_radius" => 10 deps: vars.cap_radius=10 (convert to radius)
  // cap.width (source: features.push_buttons[1].cap.width) expr="vars.cap_size" => 20 deps: vars.cap_size=20 (square cap)
  // lid.plate_thickness (source: features.push_buttons[1].lid.plate_thickness) = 2 (literal)
  // lid.protrusion (source: features.push_buttons[1].lid.protrusion) = 0 (literal)
  // lid.slack (source: features.push_buttons[1].lid.slack) = 0.3 (literal)
  // lid.snap_slack (source: features.push_buttons[1].lid.snap_slack) = 0.15 (literal)
  // lid.wall (source: features.push_buttons[1].lid.wall) = 1.8 (literal)
  // name (source: features.push_buttons[1].name) = "btn-center" (literal "btn-center")
  // shape (source: features.push_buttons[1].shape) = "circle" (literal "circle")
  // switch.height (source: features.push_buttons[1].switch.height) expr="vars.stack_height" => 15.5 deps: vars.stack_height=15.5 (switch stack height)
  // switch.pole_diameter (source: features.push_buttons[1].switch.pole_diameter) = 3 (literal)
  // switch.travel (source: features.push_buttons[1].switch.travel) = 0.8 (literal)
  // x (source: features.push_buttons[1].x) expr="vars.button_center" => 30 deps: vars.button_center=30 (align row to center)
  // y (source: features.push_buttons[1].y) expr="vars.button_row_y" => 25 deps: vars.button_row_y=25 (keep buttons toward top edge)
  [30, 25, 20, 20, 10, 0, 15.5, 0.8, 3, undef, yappCircle, undef, undef, 1.8, 2, 0.3, 0.15],
// pushButtons[2] ← features.push_buttons[2]
  // cap.length (source: features.push_buttons[2].cap.length) expr="vars.cap_size" => 20 deps: vars.cap_size=20 (square cap)
  // cap.radius (source: features.push_buttons[2].cap.radius) expr="vars.cap_radius" => 10 deps: vars.cap_radius=10 (convert to radius)
  // cap.width (source: features.push_buttons[2].cap.width) expr="vars.cap_size" => 20 deps: vars.cap_size=20 (square cap)
  // lid.plate_thickness (source: features.push_buttons[2].lid.plate_thickness) = 2 (literal)
  // lid.protrusion (source: features.push_buttons[2].lid.protrusion) = 0 (literal)
  // lid.slack (source: features.push_buttons[2].lid.slack) = 0.3 (literal)
  // lid.snap_slack (source: features.push_buttons[2].lid.snap_slack) = 0.15 (literal)
  // lid.wall (source: features.push_buttons[2].lid.wall) = 1.8 (literal)
  // name (source: features.push_buttons[2].name) = "btn-right" (literal "btn-right")
  // shape (source: features.push_buttons[2].shape) = "circle" (literal "circle")
  // switch.height (source: features.push_buttons[2].switch.height) expr="vars.stack_height" => 15.5 deps: vars.stack_height=15.5 (switch stack height)
  // switch.pole_diameter (source: features.push_buttons[2].switch.pole_diameter) = 3 (literal)
  // switch.travel (source: features.push_buttons[2].switch.travel) = 0.8 (literal)
  // x (source: features.push_buttons[2].x) expr="vars.button_center + vars.button_spacing" => 46 deps: vars.button_center=30 (align row to center), vars.button_spacing=16 (distance center-to-center)
  // y (source: features.push_buttons[2].y) expr="vars.button_row_y" => 25 deps: vars.button_row_y=25 (keep buttons toward top edge)
  [46, 25, 20, 20, 10, 0, 15.5, 0.8, 3, undef, yappCircle, undef, undef, 1.8, 2, 0.3, 0.15]
];


YAPPgenerate();
