// Generated by yappgen (MVP)
include <YAPPgenerator_v3.scad>

printSwitchExtenders = false;
// pcbLength (source: pcb.length) = 90 (literal)
pcbLength = 90;
// pcbWidth (source: pcb.width) = 70 (literal)
pcbWidth = 70;
// pcbThickness (source: pcb.thickness) = 1.6 (literal)
pcbThickness = 1.6;
// standoffHeight (source: pcb.z_clearance) = 4 (literal)
standoffHeight = 4;
// standoffDiameter (source: pcb.standoffs.diameter) = 6.5 (literal)
standoffDiameter = 6.5;
// standoffPinDiameter (source: pcb.standoffs.screw_d) = 3 (literal)
standoffPinDiameter = 3;
// standoffHoleSlack (source: tolerances.holes) = 0.45 (literal)
standoffHoleSlack = 0.45;
// wallThickness (source: enclosure.wall.thickness) = 2.6 (literal)
wallThickness = 2.6;
// basePlaneThickness (source: enclosure.base.thickness) = 2.2 (literal)
basePlaneThickness = 2.2;
// lidPlaneThickness (source: enclosure.lid.thickness) = 2 (literal)
lidPlaneThickness = 2;
// baseWallHeight (source: enclosure.base.wall_height) expr="pcb.z_clearance + pcb.thickness + 6.0" => 11.6 deps: pcb.z_clearance=4, pcb.thickness=1.6
baseWallHeight = 11.6;
// lidWallHeight (source: enclosure.lid.wall_height) expr="vars.top_clearance" => 45 deps: vars.top_clearance=45
lidWallHeight = 45;
// ridgeHeight (source: enclosure.ridge.height) = 6 (literal)
ridgeHeight = 6;
// roundRadius (source: enclosure.wall.fillet_radius) = 3 (literal)
roundRadius = 3;
// paddingFront (source: enclosure.wall.clearance) = 2 (literal)
paddingFront = 2;
// paddingBack (source: enclosure.wall.clearance) = 2 (literal)
paddingBack = 2;
// paddingLeft (source: enclosure.wall.clearance) = 2 (literal)
paddingLeft = 2;
// paddingRight (source: enclosure.wall.clearance) = 2 (literal)
paddingRight = 2;

pcbStands =
[
// pcbStands[0] ← features.pcb_stands[0]
  // diameter (source: features.pcb_stands[0].diameter) expr="pcb.standoffs.diameter" => 6.5 deps: pcb.standoffs.diameter=6.5
  // fillet_radius (source: features.pcb_stands[0].fillet_radius) = 1.5 (literal)
  // pin_diameter (source: features.pcb_stands[0].pin_diameter) expr="vars.standoff_pin_d" => 3.2 deps: vars.standoff_pin_d=3.2
  // x (source: features.pcb_stands[0].x) expr="vars.hole_offset_x" => 2.5 deps: vars.hole_offset_x=2.5
  // y (source: features.pcb_stands[0].y) expr="vars.hole_offset_y" => 2.5 deps: vars.hole_offset_y=2.5
  [2.5, 2.5, undef, undef, 6.5, 3.2, undef, 1.5, undef],
// pcbStands[1] ← features.pcb_stands[1]
  // diameter (source: features.pcb_stands[1].diameter) expr="pcb.standoffs.diameter" => 6.5 deps: pcb.standoffs.diameter=6.5
  // fillet_radius (source: features.pcb_stands[1].fillet_radius) = 1.5 (literal)
  // pin_diameter (source: features.pcb_stands[1].pin_diameter) expr="vars.standoff_pin_d" => 3.2 deps: vars.standoff_pin_d=3.2
  // x (source: features.pcb_stands[1].x) expr="pcb.length - vars.hole_offset_x" => 87.5 deps: pcb.length=90, vars.hole_offset_x=2.5
  // y (source: features.pcb_stands[1].y) expr="vars.hole_offset_y" => 2.5 deps: vars.hole_offset_y=2.5
  [87.5, 2.5, undef, undef, 6.5, 3.2, undef, 1.5, undef],
// pcbStands[2] ← features.pcb_stands[2]
  // diameter (source: features.pcb_stands[2].diameter) expr="pcb.standoffs.diameter" => 6.5 deps: pcb.standoffs.diameter=6.5
  // fillet_radius (source: features.pcb_stands[2].fillet_radius) = 1.5 (literal)
  // pin_diameter (source: features.pcb_stands[2].pin_diameter) expr="vars.standoff_pin_d" => 3.2 deps: vars.standoff_pin_d=3.2
  // x (source: features.pcb_stands[2].x) expr="pcb.length - vars.hole_offset_x" => 87.5 deps: pcb.length=90, vars.hole_offset_x=2.5
  // y (source: features.pcb_stands[2].y) expr="pcb.width - vars.hole_offset_y" => 67.5 deps: pcb.width=70, vars.hole_offset_y=2.5
  [87.5, 67.5, undef, undef, 6.5, 3.2, undef, 1.5, undef],
// pcbStands[3] ← features.pcb_stands[3]
  // diameter (source: features.pcb_stands[3].diameter) expr="pcb.standoffs.diameter" => 6.5 deps: pcb.standoffs.diameter=6.5
  // fillet_radius (source: features.pcb_stands[3].fillet_radius) = 1.5 (literal)
  // pin_diameter (source: features.pcb_stands[3].pin_diameter) expr="vars.standoff_pin_d" => 3.2 deps: vars.standoff_pin_d=3.2
  // x (source: features.pcb_stands[3].x) expr="vars.hole_offset_x" => 2.5 deps: vars.hole_offset_x=2.5
  // y (source: features.pcb_stands[3].y) expr="pcb.width - vars.hole_offset_y" => 67.5 deps: pcb.width=70, vars.hole_offset_y=2.5
  [2.5, 67.5, undef, undef, 6.5, 3.2, undef, 1.5, undef]
];

cutoutsLid =
[
  [49.6, 39.6, 38, 19, 1.5, yappRoundedRect, undef, undef],
  [21.6, 56.6, 0, 0, 14.5, yappCircle, undef, undef],
  [49.6, 56.6, 0, 0, 14.5, yappCircle, undef, undef],
  [77.6, 56.6, 0, 0, 14.5, yappCircle, undef, undef]
];


YAPPgenerate();
