// Generated by yappgen (MVP)
include <YAPPgenerator_v3.scad>

// YAML pcb:
//   pcb:
//       length: 90
//       standoffs:
//           diameter: 6.5
//           hole_slack: 0.4
//           screw_d: 3
//       thickness: 1.6
//       width: 70
//       z_clearance: 4

// YAML vars:
//   vars:
//       button_clearance: 1
//       button_diameter: 27
//       button_radius: button_diameter / 2
//       button_row_center: pcb.length / 2
//       button_row_y: pcb.width - 18.0
//       button_spacing: 28
//       button_stack_height: 40
//       display_center_x: pcb.length / 2
//       display_center_y: pcb.width / 2
//       display_center_z: 24
//       display_height: 17
//       display_width: 36
//       hole_offset_x: (pcb.length - 85.0) / 2
//       hole_offset_y: (pcb.width - 65.0) / 2
//       standoff_pin_d: 3.2
//       top_clearance: 45

// YAML enclosure:
//   enclosure:
//       base:
//           thickness: 2.2
//           wall_height: pcb.z_clearance + pcb.thickness + 6.0
//       lid:
//           thickness: 2
//           wall_height: vars.top_clearance
//       ridge:
//           gap: 0.5
//           height: 6
//           slack: 0.25
//       wall:
//           clearance: 2
//           fillet_radius: 3
//           thickness: 2.6


printSwitchExtenders = false;
// pcbLength (source: pcb.length) = 90 (literal)
pcbLength = 90;
// pcbWidth (source: pcb.width) = 70 (literal)
pcbWidth = 70;
// pcbThickness (source: pcb.thickness) = 1.6 (literal)
pcbThickness = 1.6;
// standoffHeight (source: pcb.z_clearance) = 4 (literal)
standoffHeight = 4;
// standoffDiameter (source: pcb.standoffs.diameter) = 6.5 (literal)
standoffDiameter = 6.5;
// standoffPinDiameter (source: pcb.standoffs.screw_d) = 3 (literal)
standoffPinDiameter = 3;
// standoffHoleSlack (source: tolerances.holes) = 0.45 (literal)
standoffHoleSlack = 0.45;
// wallThickness (source: enclosure.wall.thickness) = 2.6 (literal)
wallThickness = 2.6;
// basePlaneThickness (source: enclosure.base.thickness) = 2.2 (literal)
basePlaneThickness = 2.2;
// lidPlaneThickness (source: enclosure.lid.thickness) = 2 (literal)
lidPlaneThickness = 2;
// baseWallHeight (source: enclosure.base.wall_height) expr="pcb.z_clearance + pcb.thickness + 6.0" => 11.6 deps: pcb.z_clearance=4, pcb.thickness=1.6
baseWallHeight = 11.6;
// lidWallHeight (source: enclosure.lid.wall_height) expr="vars.top_clearance" => 45 deps: vars.top_clearance=45
lidWallHeight = 45;
// ridgeHeight (source: enclosure.ridge.height) = 6 (literal)
ridgeHeight = 6;
// roundRadius (source: enclosure.wall.fillet_radius) = 3 (literal)
roundRadius = 3;
// paddingFront (source: enclosure.wall.clearance) = 2 (literal)
paddingFront = 2;
// paddingBack (source: enclosure.wall.clearance) = 2 (literal)
paddingBack = 2;
// paddingLeft (source: enclosure.wall.clearance) = 2 (literal)
paddingLeft = 2;
// paddingRight (source: enclosure.wall.clearance) = 2 (literal)
paddingRight = 2;

// YAPP pcbStands row: [x, y, height?, pcb_gap?, diameter?, pin_diameter?, hole_slack?, fillet_radius?, pin_length?]
pcbStands =
[
// YAML features.pcb_stands[0]:
//   diameter: pcb.standoffs.diameter
//   fillet_radius: 1.5
//   pin_diameter: vars.standoff_pin_d
//   x: vars.hole_offset_x
//   "y": vars.hole_offset_y
// pcbStands[0] ← features.pcb_stands[0]
  // diameter (source: features.pcb_stands[0].diameter) expr="pcb.standoffs.diameter" => 6.5 deps: pcb.standoffs.diameter=6.5
  // fillet_radius (source: features.pcb_stands[0].fillet_radius) = 1.5 (literal)
  // pin_diameter (source: features.pcb_stands[0].pin_diameter) expr="vars.standoff_pin_d" => 3.2 deps: vars.standoff_pin_d=3.2
  // x (source: features.pcb_stands[0].x) expr="vars.hole_offset_x" => 2.5 deps: vars.hole_offset_x=2.5
  // y (source: features.pcb_stands[0].y) expr="vars.hole_offset_y" => 2.5 deps: vars.hole_offset_y=2.5

  [2.5, 2.5, undef, undef, 6.5, 3.2, undef, 1.5, undef],

// YAML features.pcb_stands[1]:
//   diameter: pcb.standoffs.diameter
//   fillet_radius: 1.5
//   pin_diameter: vars.standoff_pin_d
//   x: pcb.length - vars.hole_offset_x
//   "y": vars.hole_offset_y
// pcbStands[1] ← features.pcb_stands[1]
  // diameter (source: features.pcb_stands[1].diameter) expr="pcb.standoffs.diameter" => 6.5 deps: pcb.standoffs.diameter=6.5
  // fillet_radius (source: features.pcb_stands[1].fillet_radius) = 1.5 (literal)
  // pin_diameter (source: features.pcb_stands[1].pin_diameter) expr="vars.standoff_pin_d" => 3.2 deps: vars.standoff_pin_d=3.2
  // x (source: features.pcb_stands[1].x) expr="pcb.length - vars.hole_offset_x" => 87.5 deps: pcb.length=90, vars.hole_offset_x=2.5
  // y (source: features.pcb_stands[1].y) expr="vars.hole_offset_y" => 2.5 deps: vars.hole_offset_y=2.5

  [87.5, 2.5, undef, undef, 6.5, 3.2, undef, 1.5, undef],

// YAML features.pcb_stands[2]:
//   diameter: pcb.standoffs.diameter
//   fillet_radius: 1.5
//   pin_diameter: vars.standoff_pin_d
//   x: pcb.length - vars.hole_offset_x
//   "y": pcb.width - vars.hole_offset_y
// pcbStands[2] ← features.pcb_stands[2]
  // diameter (source: features.pcb_stands[2].diameter) expr="pcb.standoffs.diameter" => 6.5 deps: pcb.standoffs.diameter=6.5
  // fillet_radius (source: features.pcb_stands[2].fillet_radius) = 1.5 (literal)
  // pin_diameter (source: features.pcb_stands[2].pin_diameter) expr="vars.standoff_pin_d" => 3.2 deps: vars.standoff_pin_d=3.2
  // x (source: features.pcb_stands[2].x) expr="pcb.length - vars.hole_offset_x" => 87.5 deps: pcb.length=90, vars.hole_offset_x=2.5
  // y (source: features.pcb_stands[2].y) expr="pcb.width - vars.hole_offset_y" => 67.5 deps: pcb.width=70, vars.hole_offset_y=2.5

  [87.5, 67.5, undef, undef, 6.5, 3.2, undef, 1.5, undef],

// YAML features.pcb_stands[3]:
//   diameter: pcb.standoffs.diameter
//   fillet_radius: 1.5
//   pin_diameter: vars.standoff_pin_d
//   x: vars.hole_offset_x
//   "y": pcb.width - vars.hole_offset_y
// pcbStands[3] ← features.pcb_stands[3]
  // diameter (source: features.pcb_stands[3].diameter) expr="pcb.standoffs.diameter" => 6.5 deps: pcb.standoffs.diameter=6.5
  // fillet_radius (source: features.pcb_stands[3].fillet_radius) = 1.5 (literal)
  // pin_diameter (source: features.pcb_stands[3].pin_diameter) expr="vars.standoff_pin_d" => 3.2 deps: vars.standoff_pin_d=3.2
  // x (source: features.pcb_stands[3].x) expr="vars.hole_offset_x" => 2.5 deps: vars.hole_offset_x=2.5
  // y (source: features.pcb_stands[3].y) expr="pcb.width - vars.hole_offset_y" => 67.5 deps: pcb.width=70, vars.hole_offset_y=2.5

  [2.5, 67.5, undef, undef, 6.5, 3.2, undef, 1.5, undef]
];

// YAPP cutouts row: [pos0, pos1, width, length, radius, shape_flag, depth?, angle?, extras...]
// Extras may include polygon presets, mask definitions, coordinate/origin flags, yappNoFillet, [yappPCBName, pcb_name].
cutoutsLid =
[
// YAML features.cutouts[0]:
//   face: lid
//   from_face_back: enclosure.wall.clearance + enclosure.wall.thickness + vars.display_center_x
//   from_face_left: enclosure.wall.clearance + enclosure.wall.thickness + vars.display_center_y
//   length: vars.display_height + 2.0
//   name: display-window-lid
//   radius: 1.5
//   shape: rounded_rect
//   width: vars.display_width + 2.0
// cutoutsLid[0] ← features.cutouts[0]
  // face (source: features.cutouts[0].face) = "lid" (literal "lid")
  // from_face_back (source: features.cutouts[0].from_face_back) expr="enclosure.wall.clearance + enclosure.wall.thickness + vars.display_center_x" => 49.6 deps: enclosure.wall.clearance=2, enclosure.wall.thickness=2.6, vars.display_center_x=45
  // from_face_left (source: features.cutouts[0].from_face_left) expr="enclosure.wall.clearance + enclosure.wall.thickness + vars.display_center_y" => 39.6 deps: enclosure.wall.clearance=2, enclosure.wall.thickness=2.6, vars.display_center_y=35
  // length (source: features.cutouts[0].length) expr="vars.display_height + 2.0" => 19 deps: vars.display_height=17
  // name (source: features.cutouts[0].name) = "display-window-lid" (literal "display-window-lid")
  // radius (source: features.cutouts[0].radius) = 1.5 (literal)
  // shape (source: features.cutouts[0].shape) = "rounded_rect" (literal "rounded_rect")
  // width (source: features.cutouts[0].width) expr="vars.display_width + 2.0" => 38 deps: vars.display_width=36

  [49.6, 39.6, 38, 19, 1.5, yappRoundedRect, undef, undef],

// YAML features.cutouts[1]:
//   face: lid
//   from_face_back: enclosure.wall.clearance + enclosure.wall.thickness + (vars.button_row_center - vars.button_spacing)
//   from_face_left: enclosure.wall.clearance + enclosure.wall.thickness + vars.button_row_y
//   name: button-left-cutout
//   radius: vars.button_radius + vars.button_clearance
//   shape: circle
// cutoutsLid[1] ← features.cutouts[1]
  // face (source: features.cutouts[1].face) = "lid" (literal "lid")
  // from_face_back (source: features.cutouts[1].from_face_back) expr="enclosure.wall.clearance + enclosure.wall.thickness + (vars.button_row_center - vars.button_spacing)" => 21.6 deps: enclosure.wall.clearance=2, enclosure.wall.thickness=2.6, vars.button_row_center=45, vars.button_spacing=28
  // from_face_left (source: features.cutouts[1].from_face_left) expr="enclosure.wall.clearance + enclosure.wall.thickness + vars.button_row_y" => 56.6 deps: enclosure.wall.clearance=2, enclosure.wall.thickness=2.6, vars.button_row_y=52
  // name (source: features.cutouts[1].name) = "button-left-cutout" (literal "button-left-cutout")
  // radius (source: features.cutouts[1].radius) expr="vars.button_radius + vars.button_clearance" => 14.5 deps: vars.button_radius=13.5, vars.button_clearance=1
  // shape (source: features.cutouts[1].shape) = "circle" (literal "circle")

  [21.6, 56.6, 0, 0, 14.5, yappCircle, undef, undef],

// YAML features.cutouts[2]:
//   face: lid
//   from_face_back: enclosure.wall.clearance + enclosure.wall.thickness + vars.button_row_center
//   from_face_left: enclosure.wall.clearance + enclosure.wall.thickness + vars.button_row_y
//   name: button-center-cutout
//   radius: vars.button_radius + vars.button_clearance
//   shape: circle
// cutoutsLid[2] ← features.cutouts[2]
  // face (source: features.cutouts[2].face) = "lid" (literal "lid")
  // from_face_back (source: features.cutouts[2].from_face_back) expr="enclosure.wall.clearance + enclosure.wall.thickness + vars.button_row_center" => 49.6 deps: enclosure.wall.clearance=2, enclosure.wall.thickness=2.6, vars.button_row_center=45
  // from_face_left (source: features.cutouts[2].from_face_left) expr="enclosure.wall.clearance + enclosure.wall.thickness + vars.button_row_y" => 56.6 deps: enclosure.wall.clearance=2, enclosure.wall.thickness=2.6, vars.button_row_y=52
  // name (source: features.cutouts[2].name) = "button-center-cutout" (literal "button-center-cutout")
  // radius (source: features.cutouts[2].radius) expr="vars.button_radius + vars.button_clearance" => 14.5 deps: vars.button_radius=13.5, vars.button_clearance=1
  // shape (source: features.cutouts[2].shape) = "circle" (literal "circle")

  [49.6, 56.6, 0, 0, 14.5, yappCircle, undef, undef],

// YAML features.cutouts[3]:
//   face: lid
//   from_face_back: enclosure.wall.clearance + enclosure.wall.thickness + (vars.button_row_center + vars.button_spacing)
//   from_face_left: enclosure.wall.clearance + enclosure.wall.thickness + vars.button_row_y
//   name: button-right-cutout
//   radius: vars.button_radius + vars.button_clearance
//   shape: circle
// cutoutsLid[3] ← features.cutouts[3]
  // face (source: features.cutouts[3].face) = "lid" (literal "lid")
  // from_face_back (source: features.cutouts[3].from_face_back) expr="enclosure.wall.clearance + enclosure.wall.thickness + (vars.button_row_center + vars.button_spacing)" => 77.6 deps: enclosure.wall.clearance=2, enclosure.wall.thickness=2.6, vars.button_row_center=45, vars.button_spacing=28
  // from_face_left (source: features.cutouts[3].from_face_left) expr="enclosure.wall.clearance + enclosure.wall.thickness + vars.button_row_y" => 56.6 deps: enclosure.wall.clearance=2, enclosure.wall.thickness=2.6, vars.button_row_y=52
  // name (source: features.cutouts[3].name) = "button-right-cutout" (literal "button-right-cutout")
  // radius (source: features.cutouts[3].radius) expr="vars.button_radius + vars.button_clearance" => 14.5 deps: vars.button_radius=13.5, vars.button_clearance=1
  // shape (source: features.cutouts[3].shape) = "circle" (literal "circle")

  [77.6, 56.6, 0, 0, 14.5, yappCircle, undef, undef]
];


YAPPgenerate();
