// Generated by yappgen (MVP)
include <../YAPPgenerator_v3.scad>

pcbLength = 80;
pcbWidth = 50;
pcbThickness = 1.6;
standoffHeight = 3;
wallThickness = 2.5;
basePlaneThickness = 2;
lidPlaneThickness = 2;
roundRadius = 2;
paddingFront = 2;
paddingBack = 2;
paddingLeft = 2;
paddingRight = 2;

connectors =
[
  [20, 15, 5, 2, 4, 3, 7, undef, undef, undef]
];

snapJoins =
[
  [25, 8, yappLeft],
  [30, 8, yappRight]
];


YAPPgenerate();
