// Generated by yappgen (MVP)
include <../YAPPgenerator_v3.scad>

pcbLength = 70;
pcbWidth = 45;
pcbThickness = 1.6;
standoffHeight = 2.5;
wallThickness = 2;
basePlaneThickness = 1.8;
lidPlaneThickness = 1.8;
roundRadius = 2.5;
paddingFront = 2;
paddingBack = 2;
paddingLeft = 2;
paddingRight = 2;

pcbStands =
[
  [8, 8, undef, undef, undef, undef, undef, undef, undef],
  [62, 37, undef, undef, 6.5, undef, undef, undef, undef]
];

connectors =
[
  [15, 10, 4, 2.2, 4.2, 3.2, 7.5, undef, undef, undef]
];

snapJoins =
[
  [20, 7, yappFront],
  [25, 7, yappBack]
];

cutoutsBack =
[
  [25, 12, 16, 10, 2, yappRoundedRect, undef, undef]
];

cutoutsLeft =
[
  [30, 10, 8, 6, 6, yappCircleWithFlats, undef, undef]
];


YAPPgenerate();
