// Generated by yappgen (MVP)
include <../YAPPgenerator_v3.scad>

pcbLength = 60;
pcbWidth = 40;
pcbThickness = 1.6;
standoffHeight = 2;
wallThickness = 2;
basePlaneThickness = 1.5;
lidPlaneThickness = 1.5;
roundRadius = 3;
paddingFront = 2;
paddingBack = 2;
paddingLeft = 2;
paddingRight = 2;

pcbStands =
[
  [10, 10, undef, undef, 6, undef, undef, undef, undef],
  [50, 30, 3, undef, undef, undef, undef, undef, undef]
];

cutoutsFront =
[
  [20, 10, 15, 10, 0, yappRectangle, undef, undef]
];

cutoutsRight =
[
  [30, 12, 0, 0, 4, yappCircle, undef, undef]
];


YAPPgenerate();
