// Generated by yappgen (MVP)
include <YAPPgenerator_v3.scad>

// YAML pcb:
//   pcb:
//       length: 90
//       thickness: 1.6
//       width: 70
//       z_clearance: 2

// YAML enclosure:
//   enclosure:
//       base:
//           thickness: 1.8
//       dimensions:
//           length: 100
//       lid:
//           thickness: 1.6
//       ridge:
//           gap: 0.5
//           height: 5
//           slack: 0.2
//       wall:
//           thickness: 2.4


printSwitchExtenders = false;
// pcbLength (source: pcb.length) = 90 (literal)
pcbLength = 90;
// pcbWidth (source: pcb.width) = 70 (literal)
pcbWidth = 70;
// pcbThickness (source: pcb.thickness) = 1.6 (literal)
pcbThickness = 1.6;
// standoffHeight (source: pcb.z_clearance) = 2 (literal)
standoffHeight = 2;
// wallThickness (source: enclosure.wall.thickness) = 2.4 (literal)
wallThickness = 2.4;
// basePlaneThickness (source: enclosure.base.thickness) = 1.8 (literal)
basePlaneThickness = 1.8;
// lidPlaneThickness (source: enclosure.lid.thickness) = 1.6 (literal)
lidPlaneThickness = 1.6;
// ridgeHeight (source: enclosure.ridge.height) = 5 (literal)
ridgeHeight = 5;
// Target final length only
// paddingFront (source: enclosure.dimensions.length) = 100 (literal)
paddingFront = 2.6;
// Target final length only
// paddingBack (source: enclosure.dimensions.length) = 100 (literal)
paddingBack = 2.6;
paddingLeft = 1;
paddingRight = 1;


YAPPgenerate();
