// Generated by yappgen (MVP)
include <YAPPgenerator_v3.scad>

// YAML pcb:
//   pcb:
//       length: 90
//       thickness: 1.6
//       width: 70
//       z_clearance: 2

// YAML enclosure:
//   enclosure:
//       base:
//           thickness: 1.8
//       lid:
//           thickness: 1.6
//       ridge:
//           gap: 0.5
//           height: 5
//           slack: 0.2
//       wall:
//           clearance:
//               back: 1.5
//               front: 2
//               left: 1
//               right: 1
//           fillet_radius: 2
//           thickness: 2.4


printSwitchExtenders = false;
// pcbLength (source: pcb.length) = 90 (literal)
pcbLength = 90;
// pcbWidth (source: pcb.width) = 70 (literal)
pcbWidth = 70;
// pcbThickness (source: pcb.thickness) = 1.6 (literal)
pcbThickness = 1.6;
// standoffHeight (source: pcb.z_clearance) = 2 (literal)
standoffHeight = 2;
// wallThickness (source: enclosure.wall.thickness) = 2.4 (literal)
wallThickness = 2.4;
// basePlaneThickness (source: enclosure.base.thickness) = 1.8 (literal)
basePlaneThickness = 1.8;
// lidPlaneThickness (source: enclosure.lid.thickness) = 1.6 (literal)
lidPlaneThickness = 1.6;
// ridgeHeight (source: enclosure.ridge.height) = 5 (literal)
ridgeHeight = 5;
// roundRadius (source: enclosure.wall.fillet_radius) = 2 (literal)
roundRadius = 2;
// Extra clearance for front-mounted components
// paddingFront (source: enclosure.wall.clearance.front) = 2 (literal)
paddingFront = 2;
// paddingBack (source: enclosure.wall.clearance.back) = 1.5 (literal)
paddingBack = 1.5;
// paddingLeft (source: enclosure.wall.clearance.left) = 1 (literal)
paddingLeft = 1;
// paddingRight (source: enclosure.wall.clearance.right) = 1 (literal)
paddingRight = 1;


YAPPgenerate();
