// Code generated by schemagen; DO NOT EDIT.

package connectors

import (
	"testing"

	"gopkg.in/yaml.v3"
)

func TestConnectorsItem_MinimalConnector(t *testing.T) {
	var item ConnectorsItem
	input := []byte(`insert_d: 4
outside_d: 8
screw_d: 3
screw_head_d: 6
stand_height: 5
x: 10
"y": 10
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestConnectorsItem_FullFlaggedConnector(t *testing.T) {
	var item ConnectorsItem
	input := []byte(`coordinate: box_inside
corner: all
countersink: true
insert_d: 4
no_fillet: true
no_internal_fillet: true
outside_d: 8
pcb_name: Aux
screw_d: 3
screw_head_d: 6
self_threading: true
stand_height: 6
through_lid: true
x: 22
"y": 30
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestConnectorsItem_FullConnector(t *testing.T) {
	var item ConnectorsItem
	input := []byte(`fillet_radius: 1
insert_d: 4
insert_depth: 5
outside_d: 8
pcb_gap: 0.5
screw_d: 3
screw_head_d: 6
stand_height: 6
x: 20
"y": 25
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestConnectorsItemDecodeValidInput(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`insert_d: 4
outside_d: 8
screw_d: 3
screw_head_d: 6
stand_height: 5
x: 10
"y": 10
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	items, err := Decode([]map[string]any{raw})
	if err != nil {
		t.Fatalf("unexpected decode error: %v", err)
	}
	if len(items) != 1 {
		t.Fatalf("expected 1 item, got %d", len(items))
	}
}
func TestConnectorsItemDecodeMissingRequired(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`insert_d: 4
outside_d: 8
screw_d: 3
screw_head_d: 6
stand_height: 5
x: 10
"y": 10
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	delete(raw, "x")
	if _, err := Decode([]map[string]any{raw}); err == nil {
		t.Fatalf("expected error for missing required field")
	}
}

func TestConnectorsItemDecodeWrongType(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`insert_d: 4
outside_d: 8
screw_d: 3
screw_head_d: 6
stand_height: 5
x: 10
"y": 10
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	raw["x"] = map[string]any{"unexpected": "type"}
	if _, err := Decode([]map[string]any{raw}); err == nil {
		t.Fatalf("expected error for wrong type on required field")
	}
}
