// Code generated by schemagen; DO NOT EDIT.

package connectors

// ConnectorsItem describes the connectors schema.
type ConnectorsItem struct {
	// X coordinate on PCB (mm)
	X float64 `yaml:"x"`
	// Y coordinate on PCB (mm)
	Y float64 `yaml:"y"`
	// Height of connector standoff (mm)
	StandHeight float64 `yaml:"stand_height"`
	// Screw diameter (mm)
	ScrewD float64 `yaml:"screw_d"`
	// Screw head diameter (mm)
	ScrewHeadD float64 `yaml:"screw_head_d"`
	// Heat-set insert outer diameter (mm)
	InsertD float64 `yaml:"insert_d"`
	// Standoff outer diameter (mm)
	OutsideD float64 `yaml:"outside_d"`
	// Depth of heat-set insert
	InsertDepth *float64 `yaml:"insert_depth,omitempty"`
	// Gap between PCB and standoff top
	PcbGap *float64 `yaml:"pcb_gap,omitempty"`
	// Fillet radius at base
	FilletRadius *float64 `yaml:"fillet_radius,omitempty"`
	// Corner placement flags (yappAllCorners/yappFrontLeft/etc.)
	Corner *string `yaml:"corner,omitempty"`
	// Coordinate system selector (yappCoordPCB/yappCoordBox/yappCoordBoxInside)
	Coordinate *string `yaml:"coordinate,omitempty"`
	// Disable external fillets (yappNoFillet)
	NoFillet *bool `yaml:"no_fillet,omitempty"`
	// Enable yappCountersink flag
	Countersink *bool `yaml:"countersink,omitempty"`
	// Target PCB name for multi-board projects (emits [yappPCBName, value])
	PcbName *string `yaml:"pcb_name,omitempty"`
	// Reverse screw direction (yappThroughLid)
	ThroughLid *bool `yaml:"through_lid,omitempty"`
	// Enable self-threading inserts (yappSelfThreading)
	SelfThreading *bool `yaml:"self_threading,omitempty"`
	// Disable internal fillets (yappNoInternalFillet)
	NoInternalFillet *bool `yaml:"no_internal_fillet,omitempty"`
}

func (x *ConnectorsItem) ApplyDefaults() {
	if x.Corner == nil {
		v := "single"
		x.Corner = &v
	}
	if x.Coordinate == nil {
		v := "pcb"
		x.Coordinate = &v
	}
}

func (x *ConnectorsItem) CustomValidate() error {
	// Module author can add custom validation here
	return nil
}
