// Code generated by schemagen; DO NOT EDIT.

package connectors

// ConnectorsItem describes the connectors schema.
type ConnectorsItem struct {
	// X coordinate on PCB (mm)
	X float64 `yaml:"x"`
	// Y coordinate on PCB (mm)
	Y float64 `yaml:"y"`
	// Height of connector standoff (mm)
	StandHeight float64 `yaml:"stand_height"`
	// Screw diameter (mm)
	ScrewD float64 `yaml:"screw_d"`
	// Screw head diameter (mm)
	ScrewHeadD float64 `yaml:"screw_head_d"`
	// Heat-set insert outer diameter (mm)
	InsertD float64 `yaml:"insert_d"`
	// Standoff outer diameter (mm)
	OutsideD float64 `yaml:"outside_d"`
	// Depth of heat-set insert
	InsertDepth *float64 `yaml:"insert_depth,omitempty"`
	// Gap between PCB and standoff top
	PcbGap *float64 `yaml:"pcb_gap,omitempty"`
	// Fillet radius at base
	FilletRadius *float64 `yaml:"fillet_radius,omitempty"`
}

func (x *ConnectorsItem) ApplyDefaults() {
}

func (x *ConnectorsItem) CustomValidate() error {
	// Module author can add custom validation here
	return nil
}
