// Code generated by schemagen; DO NOT EDIT.

package pushbuttons

import (
	"testing"

	"gopkg.in/yaml.v3"
)

func TestPushButtonsItem_BasicRectangle(t *testing.T) {
	var item PushButtonsItem
	input := []byte(`cap:
    length: 8
    radius: 0.5
    width: 6
lid:
    protrusion: 2.5
switch:
    height: 5.5
    pole_diameter: 3.5
    travel: 1
x: 10
"y": 12
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestPushButtonsItemDecodeValidInput(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`cap:
    length: 8
    radius: 0.5
    width: 6
lid:
    protrusion: 2.5
switch:
    height: 5.5
    pole_diameter: 3.5
    travel: 1
x: 10
"y": 12
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	items, err := Decode([]map[string]any{raw})
	if err != nil {
		t.Fatalf("unexpected decode error: %v", err)
	}
	if len(items) != 1 {
		t.Fatalf("expected 1 item, got %d", len(items))
	}
}
func TestPushButtonsItemDecodeMissingRequired(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`cap:
    length: 8
    radius: 0.5
    width: 6
lid:
    protrusion: 2.5
switch:
    height: 5.5
    pole_diameter: 3.5
    travel: 1
x: 10
"y": 12
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	delete(raw, "x")
	if _, err := Decode([]map[string]any{raw}); err == nil {
		t.Fatalf("expected error for missing required field")
	}
}

func TestPushButtonsItemDecodeWrongType(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`cap:
    length: 8
    radius: 0.5
    width: 6
lid:
    protrusion: 2.5
switch:
    height: 5.5
    pole_diameter: 3.5
    travel: 1
x: 10
"y": 12
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	raw["x"] = map[string]any{"unexpected": "type"}
	if _, err := Decode([]map[string]any{raw}); err == nil {
		t.Fatalf("expected error for wrong type on required field")
	}
}
