// Code generated by schemagen; DO NOT EDIT.

package pushbuttons

// PushButtonsItem describes the push_buttons schema.
type PushButtonsItem struct {
	// Optional label used only for error messages
	Name *string `yaml:"name,omitempty"`
	// X coordinate relative to PCB origin (mm)
	X float64 `yaml:"x"`
	// Y coordinate relative to PCB origin (mm)
	Y float64 `yaml:"y"`
	// Rotation angle in degrees
	Angle *float64 `yaml:"angle,omitempty"`
	// Override default fillet radius for lid opening
	FilletRadius *float64 `yaml:"fillet_radius,omitempty"`
	// Button cap shape to map to SCAD shape flags
	Shape *string `yaml:"shape,omitempty"`
	// Preset polygon token (shapeArrow, shapeHexagon, etc.) when shape=polygon
	Polygon *string `yaml:"polygon,omitempty"`
	// Alternate alias for polygon preset (arrow, hexagon, etc.)
	PolygonPreset *string `yaml:"polygon_preset,omitempty"`
	// Legacy alias for polygon preset
	ShapePreset *string `yaml:"shape_preset,omitempty"`
	// Coordinate system flag appended after positional params
	Coordinate *string `yaml:"coordinate,omitempty"`
	// Origin flag appended after positional params
	Origin *string `yaml:"origin,omitempty"`
	// Set to true to disable automatic fillets
	NoFillet *bool `yaml:"no_fillet,omitempty"`
	// Cap geometry projected through lid opening
	Cap PushButtonsItemCap `yaml:"cap"`
	// Lid cutout and clearance settings
	Lid PushButtonsItemLid `yaml:"lid"`
	// Underlying physical switch dimensions
	Switch PushButtonsItemSwitch `yaml:"switch"`
}

// PushButtonsItemCap describes the push_buttons schema.
type PushButtonsItemCap struct {
	// Cap length or diameter (mm)
	Length float64 `yaml:"length"`
	// Cap width (ignored for circles)
	Width float64 `yaml:"width"`
	// Corner radius or circle radius
	Radius float64 `yaml:"radius"`
}

// PushButtonsItemLid describes the push_buttons schema.
type PushButtonsItemLid struct {
	// Distance cap extends above lid (mm)
	Protrusion float64 `yaml:"protrusion"`
	// Lid wall around button opening
	Wall *float64 `yaml:"wall,omitempty"`
	// Thickness of lid plate in cutout
	PlateThickness *float64 `yaml:"plate_thickness,omitempty"`
	// Clearance between cap and guide walls
	Slack *float64 `yaml:"slack,omitempty"`
	// Clearance for snap joins
	SnapSlack *float64 `yaml:"snap_slack,omitempty"`
	// Deprecated; prefer root no_fillet flag
	NoFillet *bool `yaml:"no_fillet,omitempty"`
}

// PushButtonsItemSwitch describes the push_buttons schema.
type PushButtonsItemSwitch struct {
	// Switch body height
	Height float64 `yaml:"height"`
	// Switch travel distance
	Travel float64 `yaml:"travel"`
	// Center pole diameter
	PoleDiameter float64 `yaml:"pole_diameter"`
	// Height from PCB to switch top (optional)
	TopHeight *float64 `yaml:"top_height,omitempty"`
}
