// Code generated by schemagen; DO NOT EDIT.

package pushbuttons

import (
	"testing"

	"gopkg.in/yaml.v3"
)

func TestPushButtonsItem_BasicRectangle(t *testing.T) {
	var item PushButtonsItem
	input := []byte(`cap:
    length: 8
    radius: 0.5
    width: 6
lid:
    protrusion: 2.5
switch:
    height: 5.5
    pole_diameter: 3.5
    travel: 1
x: 10
"y": 12
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}
