// Code generated by schemagen; DO NOT EDIT.

package snapjoins

import (
	"testing"

	"gopkg.in/yaml.v3"
)

func TestSnapJoinsItem_LeftSnap(t *testing.T) {
	var item SnapJoinsItem
	input := []byte(`pos: 20
side: left
width: 10
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}
