// Code generated by schemagen; DO NOT EDIT.

package snapjoins

import (
	"testing"

	"gopkg.in/yaml.v3"
)

func TestSnapJoinsItem_LeftSnap(t *testing.T) {
	var item SnapJoinsItem
	input := []byte(`pos: 20
side: left
width: 10
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestSnapJoinsItem_CenteredSymmetric(t *testing.T) {
	var item SnapJoinsItem
	input := []byte(`alignment: center
pos: 25
side: left
symmetric: true
width: 8
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestSnapJoinsItem_DiamondSnap(t *testing.T) {
	var item SnapJoinsItem
	input := []byte(`alignment: center
diamond: true
pos: 30
side: right
symmetric: true
width: 4
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}
