// Code generated by schemagen; DO NOT EDIT.

package snapjoins

import (
	"testing"

	"gopkg.in/yaml.v3"
)

func TestSnapJoinsItem_LeftSnap(t *testing.T) {
	var item SnapJoinsItem
	input := []byte(`pos: 20
side: left
width: 10
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestSnapJoinsItem_CenteredSymmetric(t *testing.T) {
	var item SnapJoinsItem
	input := []byte(`alignment: center
pos: 25
side: left
symmetric: true
width: 8
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestSnapJoinsItem_DiamondSnap(t *testing.T) {
	var item SnapJoinsItem
	input := []byte(`alignment: center
diamond: true
pos: 30
side: right
symmetric: true
width: 4
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestSnapJoinsItemDecodeValidInput(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`pos: 20
side: left
width: 10
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	items, err := Decode([]map[string]any{raw})
	if err != nil {
		t.Fatalf("unexpected decode error: %v", err)
	}
	if len(items) != 1 {
		t.Fatalf("expected 1 item, got %d", len(items))
	}
}
func TestSnapJoinsItemDecodeMissingRequired(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`pos: 20
side: left
width: 10
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	delete(raw, "pos")
	if _, err := Decode([]map[string]any{raw}); err == nil {
		t.Fatalf("expected error for missing required field")
	}
}

func TestSnapJoinsItemDecodeWrongType(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`pos: 20
side: left
width: 10
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	raw["pos"] = map[string]any{"unexpected": "type"}
	if _, err := Decode([]map[string]any{raw}); err == nil {
		t.Fatalf("expected error for wrong type on required field")
	}
}
