// Code generated by schemagen; DO NOT EDIT.

package snapjoins

// SnapJoinsItem describes the snap_joins schema.
type SnapJoinsItem struct {
	// Position along the edge (mm)
	Pos float64 `yaml:"pos"`
	// Width of snap join (mm)
	Width float64 `yaml:"width"`
	// Which side of enclosure (appended as YAPP flag)
	Side string `yaml:"side"`
}

func (x *SnapJoinsItem) ApplyDefaults() {
}

func (x *SnapJoinsItem) CustomValidate() error {
	// Module author can add custom validation here
	return nil
}
