// Code generated by schemagen; DO NOT EDIT.

package pcbstands

import (
	"testing"

	"gopkg.in/yaml.v3"
)

func TestPcbStandsItem_MinimalStand(t *testing.T) {
	var item PcbStandsItem
	input := []byte(`x: 5
"y": 5
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestPcbStandsItem_FullFlaggedStand(t *testing.T) {
	var item PcbStandsItem
	input := []byte(`coordinate: box_inside
corner: all
no_fillet: true
pcb_name: Aux Board
self_threading: true
shell_part: lid_only
treatment: hole
x: 12
"y": 18
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestPcbStandsItem_FullStand(t *testing.T) {
	var item PcbStandsItem
	input := []byte(`diameter: 6
fillet_radius: 1
height: 8
hole_slack: 0.1
pcb_gap: 0.5
pin_diameter: 2.5
pin_length: 3
x: 10
"y": 15
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}
