// Code generated by schemagen; DO NOT EDIT.

package pcbstands

import (
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func TestPcbStandsItem_MinimalStand(t *testing.T) {
	var item PcbStandsItem
	input := []byte(`x: 5
"y": 5
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestPcbStandsItem_FullFlaggedStand(t *testing.T) {
	var item PcbStandsItem
	input := []byte(`coordinate: box_inside
corner: all
no_fillet: true
pcb_name: Aux Board
self_threading: true
shell_part: lid_only
treatment: hole
x: 12
"y": 18
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestPcbStandsItem_FullStand(t *testing.T) {
	var item PcbStandsItem
	input := []byte(`diameter: 6
fillet_radius: 1
height: 8
hole_slack: 0.1
pcb_gap: 0.5
pin_diameter: 2.5
pin_length: 3
x: 10
"y": 15
`)
	if err := yaml.Unmarshal(input, &item); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestPcbStandsItemDecodeValidInput(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`x: 5
"y": 5
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	items, err := Decode([]map[string]any{raw})
	if err != nil {
		t.Fatalf("unexpected decode error: %v", err)
	}
	if len(items) != 1 {
		t.Fatalf("expected 1 item, got %d", len(items))
	}
}
func TestPcbStandsItemDecodeMissingRequired(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`x: 5
"y": 5
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	delete(raw, "x")
	if _, err := Decode([]map[string]any{raw}); err == nil {
		t.Fatalf("expected error for missing required field")
	}
}

func TestPcbStandsItemDecodeWrongType(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`x: 5
"y": 5
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	raw["x"] = "not a number"
	if _, err := Decode([]map[string]any{raw}); err == nil {
		t.Fatalf("expected error for wrong type on required field")
	}
}
func TestBuild_UsesGeneratedDecode(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`x: 5
"y": 5
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	raw["x"] = "not a number"
	if _, err := NewModule().Build([]map[string]any{raw}); err == nil {
		t.Fatalf("expected error when Build receives invalid field types")
	} else if !strings.Contains(err.Error(), "pcb_stands[0].x") {
		t.Fatalf("expected generated Decode error, got: %v", err)
	}
}

func TestBuild_ReturnsArrayDecl(t *testing.T) {
	raw := make(map[string]any)
	if err := yaml.Unmarshal([]byte(`x: 5
"y": 5
`), &raw); err != nil {
		t.Fatalf("unexpected yaml error: %v", err)
	}
	decls, err := NewModule().Build([]map[string]any{raw})
	if err != nil {
		t.Fatalf("Build returned error: %v", err)
	}
	if len(decls) == 0 {
		t.Fatalf("expected Build to return at least 1 ArrayDecl")
	}
	if decls[0].Name == "" {
		t.Fatalf("expected ArrayDecl name to be set")
	}
	if !strings.HasPrefix(decls[0].Name, "pcbStands") {
		t.Fatalf("expected ArrayDecl name to start with pcbStands, got %s", decls[0].Name)
	}
	if len(decls[0].Rows) == 0 {
		t.Fatalf("expected ArrayDecl rows to contain data")
	}
}
