// Code generated by schemagen; DO NOT EDIT.

package pcbstands

// PcbStandsItem describes the pcb_stands schema.
type PcbStandsItem struct {
	// X coordinate on PCB (mm)
	X float64 `yaml:"x"`
	// Y coordinate on PCB (mm)
	Y float64 `yaml:"y"`
	// Standoff height (defaults to standoffHeight)
	Height *float64 `yaml:"height,omitempty"`
	// Gap between PCB and standoff top
	PcbGap *float64 `yaml:"pcb_gap,omitempty"`
	// Standoff outer diameter
	Diameter *float64 `yaml:"diameter,omitempty"`
	// Center pin diameter for PCB hole
	PinDiameter *float64 `yaml:"pin_diameter,omitempty"`
	// Additional clearance for pin hole
	HoleSlack *float64 `yaml:"hole_slack,omitempty"`
	// Fillet radius at base
	FilletRadius *float64 `yaml:"fillet_radius,omitempty"`
	// Pin length extending through PCB
	PinLength *float64 `yaml:"pin_length,omitempty"`
	// Which shell part receives the standoff (maps to yappBoth/yappBaseOnly/yappLidOnly)
	ShellPart *string `yaml:"shell_part,omitempty"`
	// Whether to cut holes, pins, or top pins (maps to yappHole/yappTopPin)
	Treatment *string `yaml:"treatment,omitempty"`
	// Corner placement flags (yappAllCorners/yappFrontLeft/etc.)
	Corner *string `yaml:"corner,omitempty"`
	// Coordinate system selector (yappCoordPCB/yappCoordBox/yappCoordBoxInside)
	Coordinate *string `yaml:"coordinate,omitempty"`
	// Disable automatic fillets (yappNoFillet)
	NoFillet *bool `yaml:"no_fillet,omitempty"`
	// Target PCB name for multi-board projects (emits [yappPCBName, value])
	PcbName *string `yaml:"pcb_name,omitempty"`
	// Enable self-threading holes (yappSelfThreading)
	SelfThreading *bool `yaml:"self_threading,omitempty"`
}

func (x *PcbStandsItem) ApplyDefaults() {
	if x.ShellPart == nil {
		v := "both"
		x.ShellPart = &v
	}
	if x.Treatment == nil {
		v := "pin"
		x.Treatment = &v
	}
	if x.Corner == nil {
		v := "single"
		x.Corner = &v
	}
	if x.Coordinate == nil {
		v := "pcb"
		x.Coordinate = &v
	}
}

func (x *PcbStandsItem) CustomValidate() error {
	// Module author can add custom validation here
	return nil
}
