// Code generated by schemagen; DO NOT EDIT.

package pcbstands

// PcbStandsItem describes the pcb_stands schema.
type PcbStandsItem struct {
	// X coordinate on PCB (mm)
	X float64 `yaml:"x"`
	// Y coordinate on PCB (mm)
	Y float64 `yaml:"y"`
	// Standoff height (defaults to standoffHeight)
	Height *float64 `yaml:"height,omitempty"`
	// Gap between PCB and standoff top
	PcbGap *float64 `yaml:"pcb_gap,omitempty"`
	// Standoff outer diameter
	Diameter *float64 `yaml:"diameter,omitempty"`
	// Center pin diameter for PCB hole
	PinDiameter *float64 `yaml:"pin_diameter,omitempty"`
	// Additional clearance for pin hole
	HoleSlack *float64 `yaml:"hole_slack,omitempty"`
	// Fillet radius at base
	FilletRadius *float64 `yaml:"fillet_radius,omitempty"`
	// Pin length extending through PCB
	PinLength *float64 `yaml:"pin_length,omitempty"`
}

func (x *PcbStandsItem) ApplyDefaults() {
}

func (x *PcbStandsItem) CustomValidate() error {
	// Module author can add custom validation here
	return nil
}
